# boom_boot_debug.xdc
# Ensure this XDC has "Used in synthesis" enabled.

# Reset and BOOM tile clock/reset
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/chipyard_prcictrl_domain/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/chipyard_prcictrl_domain/resetSynchronizer/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/chipyard_prcictrl_domain/resetSynchronizer/nodeOut_member_allClocks_uncore_reset_catcher/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/chipyard_prcictrl_domain/resetSynchronizer/nodeOut_member_allClocks_uncore_reset_catcher/io_sync_reset_chain/ck_rst]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/chipyard_prcictrl_domain/resetSynchronizer/nodeOut_member_allClocks_uncore_reset_catcher/io_sync_reset_chain/output_chain/ck_rst]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_sbus_auto_fixedClockNode_anon_out_1_clock$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_sbus_auto_fixedClockNode_anon_out_1_reset$}]

# BOOM tile TileLink fetch request - expected first address: 0x00010000
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/tile_prci_domain/buffer/nodeOut_a_q/_tile_prci_domain_auto_tl_master_clock_xing_out_a_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/tile_prci_domain/buffer/nodeOut_a_q/ram_ext/_tile_prci_domain_auto_tl_master_clock_xing_out_a_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/_sbus_auto_coupler_from_boom_tile_tl_master_clock_xing_in_a_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/sbus/_sbus_auto_coupler_from_boom_tile_tl_master_clock_xing_in_a_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/sbus/system_bus_xbar/_sbus_auto_coupler_from_boom_tile_tl_master_clock_xing_in_a_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/tile_prci_domain/_sbus_auto_coupler_from_boom_tile_tl_master_clock_xing_in_a_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/tile_prci_domain/buffer/_sbus_auto_coupler_from_boom_tile_tl_master_clock_xing_in_a_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/tile_prci_domain/buffer/nodeOut_a_q/_sbus_auto_coupler_from_boom_tile_tl_master_clock_xing_in_a_ready]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_tile_prci_domain_auto_tl_master_clock_xing_out_a_bits_address$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_tile_prci_domain_auto_tl_master_clock_xing_out_a_bits_opcode$}]

# Internal BootROM request and response
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_cbus_auto_coupler_to_bootrom_fragmenter_anon_out_a_valid$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_bootrom_domain_auto_bootrom_in_a_ready$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_cbus_auto_coupler_to_bootrom_fragmenter_anon_out_a_bits_address$}]

set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_bootrom_domain_auto_bootrom_in_d_valid$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_cbus_auto_coupler_to_bootrom_fragmenter_anon_out_d_ready$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*_bootrom_domain_auto_bootrom_in_d_bits_data$}]

# External AXI memory read - expected after ROM: ARADDR = 0x80000000
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4yank/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4yank/Queue1_BundleMap_8/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/tl2axi4/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/tl2axi4/queue_arw_deq_q/axi4_mem_0_ar_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/coh_wrapper/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/coh_wrapper/cork/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4yank/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4yank/Queue1_BundleMap_18/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/tl2axi4/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/tl2axi4/queue_arw_deq_q/axi4_mem_0_ar_ready]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*(axi4_mem_0|mem_axi4_0)_ar_bits_addr$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*(axi4_mem_0|mem_axi4_0)_ar_bits_len$}]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*(axi4_mem_0|mem_axi4_0)_ar_bits_size$}]

set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/coh_wrapper/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/coh_wrapper/cork/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/coh_wrapper/cork/q/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/chiptop0/system/mbus/coupler_to_memory_controller_port_named_axi4/tl2axi4/axi4_mem_0_r_valid]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/axi4_mem_0_r_ready]
set_property MARK_DEBUG true [get_nets design_1_i/BoomCore_0/inst/axi4_mem_0_r_ready]
set_property MARK_DEBUG true [get_nets -hier -quiet -regexp {.*(axi4_mem_0|mem_axi4_0)_r_bits_data$}]

