#####################################################################################
# Processing System Peripherals IO Constraints
#####################################################################################
# DISPLAY PORT
set_property PACKAGE_PIN C12 [get_ports dp_hpd]
set_property IOSTANDARD LVCMOS18 [get_ports dp_hpd]

set_property PACKAGE_PIN Y10 [get_ports {dp_aux_p[0]}]
set_property IOSTANDARD LVDS [get_ports {dp_aux_n[0]}]
set_property IOSTANDARD LVDS [get_ports {dp_aux_p[0]}]

# GEM3 - Ethernet 1
set_property PACKAGE_PIN F12 [get_ports gem_3_mdio_mdc]
set_property IOSTANDARD LVCMOS18 [get_ports gem_3_mdio_mdc]

set_property PACKAGE_PIN E12 [get_ports gem_3_mdio_mdio_io]
set_property IOSTANDARD LVCMOS18 [get_ports gem_3_mdio_mdio_io]

set_property PACKAGE_PIN H13 [get_ports gem_3_rst]
set_property IOSTANDARD LVCMOS18 [get_ports gem_3_rst]

set_property PACKAGE_PIN H12 [get_ports gem_3_int]
set_property IOSTANDARD LVCMOS18 [get_ports gem_3_int]

# CAN 0
set_property PACKAGE_PIN D12 [get_ports can_0_pwr_dwn]
set_property IOSTANDARD LVCMOS18 [get_ports can_0_pwr_dwn]

# PCIe
set_property PACKAGE_PIN H14 [get_ports pcie_rst]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_rst]

set_property PACKAGE_PIN G14 [get_ports pcie_wake]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_wake]

# USB
set_property PACKAGE_PIN C14 [get_ports usb_sw]
set_property IOSTANDARD LVCMOS18 [get_ports usb_sw]

set_property PACKAGE_PIN B14 [get_ports usb_int]
set_property IOSTANDARD LVCMOS18 [get_ports usb_int]

#####################################################################################
# SDI IO Constraints
#####################################################################################
# Reference Clock
set_property PACKAGE_PIN B9 [get_ports {sdi_refclk_clk_n[0]}]
set_property PACKAGE_PIN B10 [get_ports {sdi_refclk_clk_p[0]}]

# SDI RX
set_property PACKAGE_PIN A4 [get_ports sdi_rxp]
set_property PACKAGE_PIN A3 [get_ports sdi_rxn]

# SDI TX
set_property PACKAGE_PIN A8 [get_ports sdi_txp]
set_property PACKAGE_PIN A7 [get_ports sdi_txn]

#####################################################################################
# 10G Ethernet Constraints
#####################################################################################
# Reference Clock
set_property PACKAGE_PIN F10 [get_ports eth_10g_refclk_p]
set_property PACKAGE_PIN F9 [get_ports eth_10g_refclk_n]

# Ethernet 10G RX
set_property PACKAGE_PIN B2 [get_ports eth_10g_rxp]
set_property PACKAGE_PIN B1 [get_ports eth_10g_rxn]

# Ethernet 10G TX
set_property PACKAGE_PIN B6 [get_ports eth_10g_txp]
set_property PACKAGE_PIN B5 [get_ports eth_10g_txn]

#####################################################################################
# PL DDR4 - 1
#####################################################################################
# Reference Clock
set_property PACKAGE_PIN AG8 [get_ports ddr4_sysclk_clk_p]
set_property PACKAGE_PIN AH8 [get_ports ddr4_sysclk_clk_n]

# Bank Address
set_property PACKAGE_PIN AK2 [get_ports {ddr4_ba[0]}]
set_property PACKAGE_PIN AJ6 [get_ports {ddr4_ba[1]}]

# Chip Select
set_property PACKAGE_PIN AJ12 [get_ports {ddr4_cs_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports ddr4_reset_n]

# Differential Clock Input
set_property PACKAGE_PIN AE9 [get_ports {ddr4_ck_t[0]}]
set_property PACKAGE_PIN AE8 [get_ports {ddr4_ck_c[0]}]

# Clock Enable
set_property PACKAGE_PIN AF1 [get_ports {ddr4_cke[0]}]

# On Die Termination
set_property PACKAGE_PIN AG9 [get_ports {ddr4_odt[0]}]

# Reset
set_property PACKAGE_PIN W9 [get_ports ddr4_reset_n]

# Activate Command Input
set_property PACKAGE_PIN AH4 [get_ports ddr4_act_n]

# Bank Group
set_property PACKAGE_PIN AF12 [get_ports {ddr4_bg[0]}]

# Address Bus
set_property PACKAGE_PIN AF7  [get_ports {ddr4_adr[0]}]
set_property PACKAGE_PIN AF8  [get_ports {ddr4_adr[1]}]
set_property PACKAGE_PIN AJ9  [get_ports {ddr4_adr[2]}]
set_property PACKAGE_PIN AH9  [get_ports {ddr4_adr[3]}]
set_property PACKAGE_PIN AK8  [get_ports {ddr4_adr[4]}]
set_property PACKAGE_PIN AK9  [get_ports {ddr4_adr[5]}]
set_property PACKAGE_PIN AG10 [get_ports {ddr4_adr[6]}]
set_property PACKAGE_PIN AF10 [get_ports {ddr4_adr[7]}]
set_property PACKAGE_PIN AK10 [get_ports {ddr4_adr[8]}]
set_property PACKAGE_PIN AJ10 [get_ports {ddr4_adr[9]}]
set_property PACKAGE_PIN AK11 [get_ports {ddr4_adr[10]}]
set_property PACKAGE_PIN AJ11 [get_ports {ddr4_adr[11]}]
set_property PACKAGE_PIN AH11 [get_ports {ddr4_adr[12]}]
set_property PACKAGE_PIN AG11 [get_ports {ddr4_adr[13]}]
set_property PACKAGE_PIN AF11 [get_ports {ddr4_adr[14]}]
set_property PACKAGE_PIN AJ7  [get_ports {ddr4_adr[15]}]
set_property PACKAGE_PIN AH7  [get_ports {ddr4_adr[16]}]

# Data Mask
set_property PACKAGE_PIN AK3 [get_ports {ddr4_dm_n[0]}]
set_property PACKAGE_PIN AH6 [get_ports {ddr4_dm_n[1]}]

# Differential Data Strode
set_property PACKAGE_PIN AG4 [get_ports {ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AG3 [get_ports {ddr4_dqs_c[0]}]
set_property PACKAGE_PIN AJ5 [get_ports {ddr4_dqs_t[1]}]
set_property PACKAGE_PIN AK5 [get_ports {ddr4_dqs_c[1]}]

# Data Bus
set_property PACKAGE_PIN AF2 [get_ports {ddr4_dq[0]}]
set_property PACKAGE_PIN AF3 [get_ports {ddr4_dq[1]}]
set_property PACKAGE_PIN AH1 [get_ports {ddr4_dq[2]}]
set_property PACKAGE_PIN AG1 [get_ports {ddr4_dq[3]}]
set_property PACKAGE_PIN AH2 [get_ports {ddr4_dq[4]}]
set_property PACKAGE_PIN AH3 [get_ports {ddr4_dq[5]}]
set_property PACKAGE_PIN AJ1 [get_ports {ddr4_dq[6]}]
set_property PACKAGE_PIN AJ2 [get_ports {ddr4_dq[7]}]
set_property PACKAGE_PIN AF5 [get_ports {ddr4_dq[8]}]
set_property PACKAGE_PIN AF6 [get_ports {ddr4_dq[9]}]
set_property PACKAGE_PIN AK4 [get_ports {ddr4_dq[10]}]
set_property PACKAGE_PIN AJ4 [get_ports {ddr4_dq[11]}]
set_property PACKAGE_PIN AK6 [get_ports {ddr4_dq[12]}]
set_property PACKAGE_PIN AK7 [get_ports {ddr4_dq[13]}]
set_property PACKAGE_PIN AG5 [get_ports {ddr4_dq[14]}]
set_property PACKAGE_PIN AG6 [get_ports {ddr4_dq[15]}]

#####################################################################################
# GPIO Constraints
#####################################################################################
# Board Configuration GPIOs
set_property PACKAGE_PIN AC13 [get_ports {board_config_gpio_tri_i[0]}]
set_property PACKAGE_PIN Y9   [get_ports {board_config_gpio_tri_i[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {board_config_gpio_tri_i[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {board_config_gpio_tri_i[1]}]

# PMOD Connector - 1 GPIOs
set_property PACKAGE_PIN AD1 [get_ports {pmod_gpio_1_tri_io[0]}]
set_property PACKAGE_PIN AE1 [get_ports {pmod_gpio_1_tri_io[1]}]
set_property PACKAGE_PIN AA6 [get_ports {pmod_gpio_1_tri_io[2]}]
set_property PACKAGE_PIN AA5 [get_ports {pmod_gpio_1_tri_io[3]}]
set_property PACKAGE_PIN AA2 [get_ports {pmod_gpio_1_tri_io[4]}]
set_property PACKAGE_PIN AA1 [get_ports {pmod_gpio_1_tri_io[5]}]
set_property PACKAGE_PIN AB1 [get_ports {pmod_gpio_1_tri_io[6]}]
set_property PACKAGE_PIN AC1 [get_ports {pmod_gpio_1_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_1_tri_io[7]}]

# PMOD Connector - 2 GPIOs
set_property PACKAGE_PIN AB9  [get_ports {pmod_gpio_2_tri_io[0]}]
set_property PACKAGE_PIN AB10 [get_ports {pmod_gpio_2_tri_io[1]}]
set_property PACKAGE_PIN AA3  [get_ports {pmod_gpio_2_tri_io[2]}]
set_property PACKAGE_PIN AB3  [get_ports {pmod_gpio_2_tri_io[3]}]
set_property PACKAGE_PIN AE2  [get_ports {pmod_gpio_2_tri_io[4]}]
set_property PACKAGE_PIN AD2  [get_ports {pmod_gpio_2_tri_io[5]}]
set_property PACKAGE_PIN Y8   [get_ports {pmod_gpio_2_tri_io[6]}]
set_property PACKAGE_PIN W8   [get_ports {pmod_gpio_2_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_gpio_2_tri_io[7]}]

# FMC Connector - 1 GPIOs
set_property PACKAGE_PIN AD5  [get_ports {fmc1_gpio_1_tri_io[0]}]
set_property PACKAGE_PIN AE5  [get_ports {fmc1_gpio_1_tri_io[1]}]
set_property PACKAGE_PIN AE18 [get_ports {fmc1_gpio_1_tri_io[2]}]
set_property PACKAGE_PIN AF18 [get_ports {fmc1_gpio_1_tri_io[3]}]
set_property PACKAGE_PIN AJ14 [get_ports {fmc1_gpio_1_tri_io[4]}]
set_property PACKAGE_PIN AK14 [get_ports {fmc1_gpio_1_tri_io[5]}]
set_property PACKAGE_PIN F16  [get_ports {fmc1_gpio_1_tri_io[6]}]
set_property PACKAGE_PIN F15  [get_ports {fmc1_gpio_1_tri_io[7]}]
set_property PACKAGE_PIN AA8  [get_ports {fmc1_gpio_1_tri_io[8]}]
set_property PACKAGE_PIN AB8  [get_ports {fmc1_gpio_1_tri_io[9]}]
set_property PACKAGE_PIN AG14 [get_ports {fmc1_gpio_1_tri_io[10]}]
set_property PACKAGE_PIN AH14 [get_ports {fmc1_gpio_1_tri_io[11]}]
set_property PACKAGE_PIN AC3  [get_ports {fmc1_gpio_1_tri_io[12]}]
set_property PACKAGE_PIN AC2  [get_ports {fmc1_gpio_1_tri_io[13]}]
set_property PACKAGE_PIN AK17 [get_ports {fmc1_gpio_1_tri_io[14]}]
set_property PACKAGE_PIN AK18 [get_ports {fmc1_gpio_1_tri_io[15]}]
set_property PACKAGE_PIN AJ16 [get_ports {fmc1_gpio_1_tri_io[16]}]
set_property PACKAGE_PIN AK16 [get_ports {fmc1_gpio_1_tri_io[17]}]
set_property PACKAGE_PIN E17  [get_ports {fmc1_gpio_1_tri_io[18]}]
set_property PACKAGE_PIN D17  [get_ports {fmc1_gpio_1_tri_io[19]}]
set_property PACKAGE_PIN AA15 [get_ports {fmc1_gpio_1_tri_io[20]}]
set_property PACKAGE_PIN AB15 [get_ports {fmc1_gpio_1_tri_io[21]}]
set_property PACKAGE_PIN K13  [get_ports {fmc1_gpio_1_tri_io[22]}]
set_property PACKAGE_PIN J12  [get_ports {fmc1_gpio_1_tri_io[23]}]
set_property PACKAGE_PIN E14  [get_ports {fmc1_gpio_1_tri_io[24]}]
set_property PACKAGE_PIN E13  [get_ports {fmc1_gpio_1_tri_io[25]}]
set_property PACKAGE_PIN AF15 [get_ports {fmc1_gpio_1_tri_io[26]}]
set_property PACKAGE_PIN AG15 [get_ports {fmc1_gpio_1_tri_io[27]}]
set_property PACKAGE_PIN AD19 [get_ports {fmc1_gpio_1_tri_io[28]}]
set_property PACKAGE_PIN AE19 [get_ports {fmc1_gpio_1_tri_io[29]}]
set_property PACKAGE_PIN AE14 [get_ports {fmc1_gpio_1_tri_io[30]}]
set_property PACKAGE_PIN AE13 [get_ports {fmc1_gpio_1_tri_io[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_1_tri_io[31]}]

set_property PACKAGE_PIN AD15 [get_ports {fmc1_gpio_2_tri_io[0]}]
set_property PACKAGE_PIN AE15 [get_ports {fmc1_gpio_2_tri_io[1]}]
set_property PACKAGE_PIN AJ15 [get_ports {fmc1_gpio_2_tri_io[2]}]
set_property PACKAGE_PIN AK15 [get_ports {fmc1_gpio_2_tri_io[3]}]
set_property PACKAGE_PIN AC14 [get_ports {fmc1_gpio_2_tri_io[4]}]
set_property PACKAGE_PIN AD14 [get_ports {fmc1_gpio_2_tri_io[5]}]
set_property PACKAGE_PIN AG13 [get_ports {fmc1_gpio_2_tri_io[6]}]
set_property PACKAGE_PIN AH13 [get_ports {fmc1_gpio_2_tri_io[7]}]
set_property PACKAGE_PIN J15  [get_ports {fmc1_gpio_2_tri_io[8]}]
set_property PACKAGE_PIN J14  [get_ports {fmc1_gpio_2_tri_io[9]}]
set_property PACKAGE_PIN K15  [get_ports {fmc1_gpio_2_tri_io[10]}]
set_property PACKAGE_PIN K14  [get_ports {fmc1_gpio_2_tri_io[11]}]
set_property PACKAGE_PIN L15  [get_ports {fmc1_gpio_2_tri_io[12]}]
set_property PACKAGE_PIN L14  [get_ports {fmc1_gpio_2_tri_io[13]}]
set_property PACKAGE_PIN A17  [get_ports {fmc1_gpio_2_tri_io[14]}]
set_property PACKAGE_PIN A16  [get_ports {fmc1_gpio_2_tri_io[15]}]
set_property PACKAGE_PIN AG18 [get_ports {fmc1_gpio_2_tri_io[16]}]
set_property PACKAGE_PIN AH18 [get_ports {fmc1_gpio_2_tri_io[17]}]
set_property PACKAGE_PIN AC17 [get_ports {fmc1_gpio_2_tri_io[18]}]
set_property PACKAGE_PIN AC18 [get_ports {fmc1_gpio_2_tri_io[19]}]
set_property PACKAGE_PIN AH17 [get_ports {fmc1_gpio_2_tri_io[20]}]
set_property PACKAGE_PIN AJ17 [get_ports {fmc1_gpio_2_tri_io[21]}]
set_property PACKAGE_PIN AA13 [get_ports {fmc1_gpio_2_tri_io[22]}]
set_property PACKAGE_PIN AB13 [get_ports {fmc1_gpio_2_tri_io[23]}]
set_property PACKAGE_PIN AG16 [get_ports {fmc1_gpio_2_tri_io[24]}]
set_property PACKAGE_PIN AH16 [get_ports {fmc1_gpio_2_tri_io[25]}]
set_property PACKAGE_PIN AK13 [get_ports {fmc1_gpio_2_tri_io[26]}]
set_property PACKAGE_PIN AK12 [get_ports {fmc1_gpio_2_tri_io[27]}]
set_property PACKAGE_PIN AA16 [get_ports {fmc1_gpio_2_tri_io[28]}]
set_property PACKAGE_PIN AB16 [get_ports {fmc1_gpio_2_tri_io[29]}]
set_property PACKAGE_PIN J16  [get_ports {fmc1_gpio_2_tri_io[30]}]
set_property PACKAGE_PIN H16  [get_ports {fmc1_gpio_2_tri_io[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_2_tri_io[31]}]

set_property PACKAGE_PIN D16  [get_ports {fmc1_gpio_3_tri_io[0]}]
set_property PACKAGE_PIN C16  [get_ports {fmc1_gpio_3_tri_io[1]}]
set_property PACKAGE_PIN B15  [get_ports {fmc1_gpio_3_tri_io[2]}]
set_property PACKAGE_PIN A15  [get_ports {fmc1_gpio_3_tri_io[3]}]
set_property PACKAGE_PIN C17  [get_ports {fmc1_gpio_3_tri_io[4]}]
set_property PACKAGE_PIN B16  [get_ports {fmc1_gpio_3_tri_io[5]}]
set_property PACKAGE_PIN AF16 [get_ports {fmc1_gpio_3_tri_io[6]}]
set_property PACKAGE_PIN AF17 [get_ports {fmc1_gpio_3_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc1_gpio_3_tri_io[7]}]

# FMC Connector - 2 GPIOs
set_property PACKAGE_PIN AA12 [get_ports {fmc2_gpio_1_tri_io[0]}]
set_property PACKAGE_PIN AA11 [get_ports {fmc2_gpio_1_tri_io[1]}]
set_property PACKAGE_PIN AB11 [get_ports {fmc2_gpio_1_tri_io[2]}]
set_property PACKAGE_PIN AC11 [get_ports {fmc2_gpio_1_tri_io[3]}]
set_property PACKAGE_PIN K12  [get_ports {fmc2_gpio_1_tri_io[4]}]
set_property PACKAGE_PIN K11  [get_ports {fmc2_gpio_1_tri_io[5]}]
set_property PACKAGE_PIN E15  [get_ports {fmc2_gpio_1_tri_io[6]}]
set_property PACKAGE_PIN D15  [get_ports {fmc2_gpio_1_tri_io[7]}]
set_property PACKAGE_PIN AC8  [get_ports {fmc2_gpio_1_tri_io[8]}]
set_property PACKAGE_PIN AC7  [get_ports {fmc2_gpio_1_tri_io[9]}]
set_property PACKAGE_PIN AC6  [get_ports {fmc2_gpio_1_tri_io[10]}]
set_property PACKAGE_PIN AD6  [get_ports {fmc2_gpio_1_tri_io[11]}]
set_property PACKAGE_PIN AC12 [get_ports {fmc2_gpio_1_tri_io[12]}]
set_property PACKAGE_PIN AD12 [get_ports {fmc2_gpio_1_tri_io[13]}]
set_property PACKAGE_PIN D14  [get_ports {fmc2_gpio_1_tri_io[14]}]
set_property PACKAGE_PIN C13  [get_ports {fmc2_gpio_1_tri_io[15]}]
set_property PACKAGE_PIN G13  [get_ports {fmc2_gpio_1_tri_io[16]}]
set_property PACKAGE_PIN F13  [get_ports {fmc2_gpio_1_tri_io[17]}]
set_property PACKAGE_PIN AB6  [get_ports {fmc2_gpio_1_tri_io[18]}]
set_property PACKAGE_PIN AB5  [get_ports {fmc2_gpio_1_tri_io[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_1_tri_io[19]}]

set_property PACKAGE_PIN AD7  [get_ports {fmc2_gpio_2_tri_io[0]}]
set_property PACKAGE_PIN AE7  [get_ports {fmc2_gpio_2_tri_io[1]}]
set_property PACKAGE_PIN AC9  [get_ports {fmc2_gpio_2_tri_io[2]}]
set_property PACKAGE_PIN AD9  [get_ports {fmc2_gpio_2_tri_io[3]}]
set_property PACKAGE_PIN AD11 [get_ports {fmc2_gpio_2_tri_io[4]}]
set_property PACKAGE_PIN AD10 [get_ports {fmc2_gpio_2_tri_io[5]}]
set_property PACKAGE_PIN AA14 [get_ports {fmc2_gpio_2_tri_io[6]}]
set_property PACKAGE_PIN AB14 [get_ports {fmc2_gpio_2_tri_io[7]}]
set_property PACKAGE_PIN B12  [get_ports {fmc2_gpio_2_tri_io[8]}]
set_property PACKAGE_PIN A12  [get_ports {fmc2_gpio_2_tri_io[9]}]
set_property PACKAGE_PIN Y7   [get_ports {fmc2_gpio_2_tri_io[10]}]
set_property PACKAGE_PIN AA7  [get_ports {fmc2_gpio_2_tri_io[11]}]
set_property PACKAGE_PIN AD4  [get_ports {fmc2_gpio_2_tri_io[12]}]
set_property PACKAGE_PIN AE4  [get_ports {fmc2_gpio_2_tri_io[13]}]
set_property PACKAGE_PIN AB4  [get_ports {fmc2_gpio_2_tri_io[14]}]
set_property PACKAGE_PIN AC4  [get_ports {fmc2_gpio_2_tri_io[15]}]
set_property PACKAGE_PIN AC16 [get_ports {fmc2_gpio_2_tri_io[16]}]
set_property PACKAGE_PIN AD16 [get_ports {fmc2_gpio_2_tri_io[17]}]
set_property PACKAGE_PIN A14  [get_ports {fmc2_gpio_2_tri_io[18]}]
set_property PACKAGE_PIN A13  [get_ports {fmc2_gpio_2_tri_io[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fmc2_gpio_2_tri_io[19]}]