// Generated by CIRCT firtool-1.75.0
module ALUExeUnit(	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [31:0] io_req_bits_uop_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [31:0] io_req_bits_uop_debug_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_rvc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [39:0] io_req_bits_uop_debug_pc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_iq_type,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [9:0]  io_req_bits_uop_fu_code,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [3:0]  io_req_bits_uop_ctrl_br_type,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_ctrl_op1_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_ctrl_op2_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_ctrl_imm_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_ctrl_csr_cmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_iw_state,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_br,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_jal,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_sfb,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [7:0]  io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_br_tag,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [3:0]  io_req_bits_uop_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_taken,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [11:0] io_req_bits_uop_csr_addr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_rxq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_prs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_prs2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_prs3,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [3:0]  io_req_bits_uop_ppred,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ppred_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_exception,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [63:0] io_req_bits_uop_exc_cause,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_bypassable,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_fence,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_fencei,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_sys_pc2epc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_unique,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_flush_on_commit,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ldst_is_rs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_ldst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_lrs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_lrs2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_lrs3,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_frs3_en,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_fp_single,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_xcpt_pf_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_xcpt_ae_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_xcpt_ma_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_bp_debug_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_bp_xcpt_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_debug_fsrc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_debug_tsrc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [64:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [64:0] io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_iresp_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_ll_iresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_ll_iresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_iresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_iresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_ll_iresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [64:0] io_ll_iresp_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_fresp_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_ll_fresp_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [7:0]  io_ll_fresp_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_ll_fresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_ll_fresp_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_ll_fresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_ll_fresp_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_fresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_fresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_ll_fresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_ll_fresp_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [64:0] io_ll_fresp_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [7:0]  io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [7:0]  io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_lsu_io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [31:0] io_lsu_io_req_bits_uop_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [31:0] io_lsu_io_req_bits_uop_debug_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_rvc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [39:0] io_lsu_io_req_bits_uop_debug_pc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_iq_type,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [9:0]  io_lsu_io_req_bits_uop_fu_code,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [3:0]  io_lsu_io_req_bits_uop_ctrl_br_type,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_ctrl_op1_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_ctrl_op2_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_ctrl_imm_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_lsu_io_req_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_ctrl_csr_cmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_iw_state,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_br,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_jal,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_sfb,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [7:0]  io_lsu_io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_br_tag,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [3:0]  io_lsu_io_req_bits_uop_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_taken,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [19:0] io_lsu_io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [11:0] io_lsu_io_req_bits_uop_csr_addr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_lsu_io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_lsu_io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_rxq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_prs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_prs2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_prs3,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [3:0]  io_lsu_io_req_bits_uop_ppred,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ppred_busy,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_exception,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [63:0] io_lsu_io_req_bits_uop_exc_cause,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_bypassable,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_lsu_io_req_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_fence,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_fencei,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_sys_pc2epc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_is_unique,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_flush_on_commit,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ldst_is_rs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_ldst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_lrs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_lrs2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_lsu_io_req_bits_uop_lrs3,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_frs3_en,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_fp_single,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_xcpt_pf_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_xcpt_ae_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_xcpt_ma_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_bp_debug_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_uop_bp_xcpt_if,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_debug_fsrc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_lsu_io_req_bits_uop_debug_tsrc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [63:0] io_lsu_io_req_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [39:0] io_lsu_io_req_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_mxcpt_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_sfence_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_sfence_bits_rs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_lsu_io_req_bits_sfence_bits_rs2,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [38:0] io_lsu_io_req_bits_sfence_bits_addr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_iresp_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_lsu_io_iresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_lsu_io_iresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_iresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_iresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_lsu_io_iresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [63:0] io_lsu_io_iresp_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_fresp_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [6:0]  io_lsu_io_fresp_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [7:0]  io_lsu_io_fresp_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_lsu_io_fresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_lsu_io_fresp_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_lsu_io_fresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_lsu_io_fresp_bits_uop_mem_size,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_fresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_fresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_lsu_io_fresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_lsu_io_fresp_bits_uop_fp_val,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [64:0] io_lsu_io_fresp_bits_data	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
);

  wire [64:0] _maddrcalc_io_resp_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:388:27]
  MemAddrCalcUnit maddrcalc (	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:388:27]
    .clock                            (clock),
    .reset                            (reset),
    .io_req_valid                     (io_req_valid & io_req_bits_uop_fu_code[2]),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14, :390:45]
    .io_req_bits_uop_uopc             (io_req_bits_uop_uopc),
    .io_req_bits_uop_inst             (io_req_bits_uop_inst),
    .io_req_bits_uop_debug_inst       (io_req_bits_uop_debug_inst),
    .io_req_bits_uop_is_rvc           (io_req_bits_uop_is_rvc),
    .io_req_bits_uop_debug_pc         (io_req_bits_uop_debug_pc),
    .io_req_bits_uop_iq_type          (io_req_bits_uop_iq_type),
    .io_req_bits_uop_fu_code          (io_req_bits_uop_fu_code),
    .io_req_bits_uop_ctrl_br_type     (io_req_bits_uop_ctrl_br_type),
    .io_req_bits_uop_ctrl_op1_sel     (io_req_bits_uop_ctrl_op1_sel),
    .io_req_bits_uop_ctrl_op2_sel     (io_req_bits_uop_ctrl_op2_sel),
    .io_req_bits_uop_ctrl_imm_sel     (io_req_bits_uop_ctrl_imm_sel),
    .io_req_bits_uop_ctrl_op_fcn      (io_req_bits_uop_ctrl_op_fcn),
    .io_req_bits_uop_ctrl_fcn_dw      (io_req_bits_uop_ctrl_fcn_dw),
    .io_req_bits_uop_ctrl_csr_cmd     (io_req_bits_uop_ctrl_csr_cmd),
    .io_req_bits_uop_ctrl_is_load     (io_req_bits_uop_ctrl_is_load),
    .io_req_bits_uop_ctrl_is_sta      (io_req_bits_uop_ctrl_is_sta),
    .io_req_bits_uop_ctrl_is_std      (io_req_bits_uop_ctrl_is_std),
    .io_req_bits_uop_iw_state         (io_req_bits_uop_iw_state),
    .io_req_bits_uop_is_br            (io_req_bits_uop_is_br),
    .io_req_bits_uop_is_jalr          (io_req_bits_uop_is_jalr),
    .io_req_bits_uop_is_jal           (io_req_bits_uop_is_jal),
    .io_req_bits_uop_is_sfb           (io_req_bits_uop_is_sfb),
    .io_req_bits_uop_br_mask          (io_req_bits_uop_br_mask),
    .io_req_bits_uop_br_tag           (io_req_bits_uop_br_tag),
    .io_req_bits_uop_ftq_idx          (io_req_bits_uop_ftq_idx),
    .io_req_bits_uop_edge_inst        (io_req_bits_uop_edge_inst),
    .io_req_bits_uop_pc_lob           (io_req_bits_uop_pc_lob),
    .io_req_bits_uop_taken            (io_req_bits_uop_taken),
    .io_req_bits_uop_imm_packed       (io_req_bits_uop_imm_packed),
    .io_req_bits_uop_csr_addr         (io_req_bits_uop_csr_addr),
    .io_req_bits_uop_rob_idx          (io_req_bits_uop_rob_idx),
    .io_req_bits_uop_ldq_idx          (io_req_bits_uop_ldq_idx),
    .io_req_bits_uop_stq_idx          (io_req_bits_uop_stq_idx),
    .io_req_bits_uop_rxq_idx          (io_req_bits_uop_rxq_idx),
    .io_req_bits_uop_pdst             (io_req_bits_uop_pdst),
    .io_req_bits_uop_prs1             (io_req_bits_uop_prs1),
    .io_req_bits_uop_prs2             (io_req_bits_uop_prs2),
    .io_req_bits_uop_prs3             (io_req_bits_uop_prs3),
    .io_req_bits_uop_ppred            (io_req_bits_uop_ppred),
    .io_req_bits_uop_prs1_busy        (io_req_bits_uop_prs1_busy),
    .io_req_bits_uop_prs2_busy        (io_req_bits_uop_prs2_busy),
    .io_req_bits_uop_prs3_busy        (io_req_bits_uop_prs3_busy),
    .io_req_bits_uop_ppred_busy       (io_req_bits_uop_ppred_busy),
    .io_req_bits_uop_stale_pdst       (io_req_bits_uop_stale_pdst),
    .io_req_bits_uop_exception        (io_req_bits_uop_exception),
    .io_req_bits_uop_exc_cause        (io_req_bits_uop_exc_cause),
    .io_req_bits_uop_bypassable       (io_req_bits_uop_bypassable),
    .io_req_bits_uop_mem_cmd          (io_req_bits_uop_mem_cmd),
    .io_req_bits_uop_mem_size         (io_req_bits_uop_mem_size),
    .io_req_bits_uop_mem_signed       (io_req_bits_uop_mem_signed),
    .io_req_bits_uop_is_fence         (io_req_bits_uop_is_fence),
    .io_req_bits_uop_is_fencei        (io_req_bits_uop_is_fencei),
    .io_req_bits_uop_is_amo           (io_req_bits_uop_is_amo),
    .io_req_bits_uop_uses_ldq         (io_req_bits_uop_uses_ldq),
    .io_req_bits_uop_uses_stq         (io_req_bits_uop_uses_stq),
    .io_req_bits_uop_is_sys_pc2epc    (io_req_bits_uop_is_sys_pc2epc),
    .io_req_bits_uop_is_unique        (io_req_bits_uop_is_unique),
    .io_req_bits_uop_flush_on_commit  (io_req_bits_uop_flush_on_commit),
    .io_req_bits_uop_ldst_is_rs1      (io_req_bits_uop_ldst_is_rs1),
    .io_req_bits_uop_ldst             (io_req_bits_uop_ldst),
    .io_req_bits_uop_lrs1             (io_req_bits_uop_lrs1),
    .io_req_bits_uop_lrs2             (io_req_bits_uop_lrs2),
    .io_req_bits_uop_lrs3             (io_req_bits_uop_lrs3),
    .io_req_bits_uop_ldst_val         (io_req_bits_uop_ldst_val),
    .io_req_bits_uop_dst_rtype        (io_req_bits_uop_dst_rtype),
    .io_req_bits_uop_lrs1_rtype       (io_req_bits_uop_lrs1_rtype),
    .io_req_bits_uop_lrs2_rtype       (io_req_bits_uop_lrs2_rtype),
    .io_req_bits_uop_frs3_en          (io_req_bits_uop_frs3_en),
    .io_req_bits_uop_fp_val           (io_req_bits_uop_fp_val),
    .io_req_bits_uop_fp_single        (io_req_bits_uop_fp_single),
    .io_req_bits_uop_xcpt_pf_if       (io_req_bits_uop_xcpt_pf_if),
    .io_req_bits_uop_xcpt_ae_if       (io_req_bits_uop_xcpt_ae_if),
    .io_req_bits_uop_xcpt_ma_if       (io_req_bits_uop_xcpt_ma_if),
    .io_req_bits_uop_bp_debug_if      (io_req_bits_uop_bp_debug_if),
    .io_req_bits_uop_bp_xcpt_if       (io_req_bits_uop_bp_xcpt_if),
    .io_req_bits_uop_debug_fsrc       (io_req_bits_uop_debug_fsrc),
    .io_req_bits_uop_debug_tsrc       (io_req_bits_uop_debug_tsrc),
    .io_req_bits_rs1_data             (io_req_bits_rs1_data),
    .io_req_bits_rs2_data             (io_req_bits_rs2_data),
    .io_resp_valid                    (io_lsu_io_req_valid),
    .io_resp_bits_uop_uopc            (io_lsu_io_req_bits_uop_uopc),
    .io_resp_bits_uop_inst            (io_lsu_io_req_bits_uop_inst),
    .io_resp_bits_uop_debug_inst      (io_lsu_io_req_bits_uop_debug_inst),
    .io_resp_bits_uop_is_rvc          (io_lsu_io_req_bits_uop_is_rvc),
    .io_resp_bits_uop_debug_pc        (io_lsu_io_req_bits_uop_debug_pc),
    .io_resp_bits_uop_iq_type         (io_lsu_io_req_bits_uop_iq_type),
    .io_resp_bits_uop_fu_code         (io_lsu_io_req_bits_uop_fu_code),
    .io_resp_bits_uop_ctrl_br_type    (io_lsu_io_req_bits_uop_ctrl_br_type),
    .io_resp_bits_uop_ctrl_op1_sel    (io_lsu_io_req_bits_uop_ctrl_op1_sel),
    .io_resp_bits_uop_ctrl_op2_sel    (io_lsu_io_req_bits_uop_ctrl_op2_sel),
    .io_resp_bits_uop_ctrl_imm_sel    (io_lsu_io_req_bits_uop_ctrl_imm_sel),
    .io_resp_bits_uop_ctrl_op_fcn     (io_lsu_io_req_bits_uop_ctrl_op_fcn),
    .io_resp_bits_uop_ctrl_fcn_dw     (io_lsu_io_req_bits_uop_ctrl_fcn_dw),
    .io_resp_bits_uop_ctrl_csr_cmd    (io_lsu_io_req_bits_uop_ctrl_csr_cmd),
    .io_resp_bits_uop_ctrl_is_load    (io_lsu_io_req_bits_uop_ctrl_is_load),
    .io_resp_bits_uop_ctrl_is_sta     (io_lsu_io_req_bits_uop_ctrl_is_sta),
    .io_resp_bits_uop_ctrl_is_std     (io_lsu_io_req_bits_uop_ctrl_is_std),
    .io_resp_bits_uop_iw_state        (io_lsu_io_req_bits_uop_iw_state),
    .io_resp_bits_uop_is_br           (io_lsu_io_req_bits_uop_is_br),
    .io_resp_bits_uop_is_jalr         (io_lsu_io_req_bits_uop_is_jalr),
    .io_resp_bits_uop_is_jal          (io_lsu_io_req_bits_uop_is_jal),
    .io_resp_bits_uop_is_sfb          (io_lsu_io_req_bits_uop_is_sfb),
    .io_resp_bits_uop_br_mask         (io_lsu_io_req_bits_uop_br_mask),
    .io_resp_bits_uop_br_tag          (io_lsu_io_req_bits_uop_br_tag),
    .io_resp_bits_uop_ftq_idx         (io_lsu_io_req_bits_uop_ftq_idx),
    .io_resp_bits_uop_edge_inst       (io_lsu_io_req_bits_uop_edge_inst),
    .io_resp_bits_uop_pc_lob          (io_lsu_io_req_bits_uop_pc_lob),
    .io_resp_bits_uop_taken           (io_lsu_io_req_bits_uop_taken),
    .io_resp_bits_uop_imm_packed      (io_lsu_io_req_bits_uop_imm_packed),
    .io_resp_bits_uop_csr_addr        (io_lsu_io_req_bits_uop_csr_addr),
    .io_resp_bits_uop_rob_idx         (io_lsu_io_req_bits_uop_rob_idx),
    .io_resp_bits_uop_ldq_idx         (io_lsu_io_req_bits_uop_ldq_idx),
    .io_resp_bits_uop_stq_idx         (io_lsu_io_req_bits_uop_stq_idx),
    .io_resp_bits_uop_rxq_idx         (io_lsu_io_req_bits_uop_rxq_idx),
    .io_resp_bits_uop_pdst            (io_lsu_io_req_bits_uop_pdst),
    .io_resp_bits_uop_prs1            (io_lsu_io_req_bits_uop_prs1),
    .io_resp_bits_uop_prs2            (io_lsu_io_req_bits_uop_prs2),
    .io_resp_bits_uop_prs3            (io_lsu_io_req_bits_uop_prs3),
    .io_resp_bits_uop_ppred           (io_lsu_io_req_bits_uop_ppred),
    .io_resp_bits_uop_prs1_busy       (io_lsu_io_req_bits_uop_prs1_busy),
    .io_resp_bits_uop_prs2_busy       (io_lsu_io_req_bits_uop_prs2_busy),
    .io_resp_bits_uop_prs3_busy       (io_lsu_io_req_bits_uop_prs3_busy),
    .io_resp_bits_uop_ppred_busy      (io_lsu_io_req_bits_uop_ppred_busy),
    .io_resp_bits_uop_stale_pdst      (io_lsu_io_req_bits_uop_stale_pdst),
    .io_resp_bits_uop_exception       (io_lsu_io_req_bits_uop_exception),
    .io_resp_bits_uop_exc_cause       (io_lsu_io_req_bits_uop_exc_cause),
    .io_resp_bits_uop_bypassable      (io_lsu_io_req_bits_uop_bypassable),
    .io_resp_bits_uop_mem_cmd         (io_lsu_io_req_bits_uop_mem_cmd),
    .io_resp_bits_uop_mem_size        (io_lsu_io_req_bits_uop_mem_size),
    .io_resp_bits_uop_mem_signed      (io_lsu_io_req_bits_uop_mem_signed),
    .io_resp_bits_uop_is_fence        (io_lsu_io_req_bits_uop_is_fence),
    .io_resp_bits_uop_is_fencei       (io_lsu_io_req_bits_uop_is_fencei),
    .io_resp_bits_uop_is_amo          (io_lsu_io_req_bits_uop_is_amo),
    .io_resp_bits_uop_uses_ldq        (io_lsu_io_req_bits_uop_uses_ldq),
    .io_resp_bits_uop_uses_stq        (io_lsu_io_req_bits_uop_uses_stq),
    .io_resp_bits_uop_is_sys_pc2epc   (io_lsu_io_req_bits_uop_is_sys_pc2epc),
    .io_resp_bits_uop_is_unique       (io_lsu_io_req_bits_uop_is_unique),
    .io_resp_bits_uop_flush_on_commit (io_lsu_io_req_bits_uop_flush_on_commit),
    .io_resp_bits_uop_ldst_is_rs1     (io_lsu_io_req_bits_uop_ldst_is_rs1),
    .io_resp_bits_uop_ldst            (io_lsu_io_req_bits_uop_ldst),
    .io_resp_bits_uop_lrs1            (io_lsu_io_req_bits_uop_lrs1),
    .io_resp_bits_uop_lrs2            (io_lsu_io_req_bits_uop_lrs2),
    .io_resp_bits_uop_lrs3            (io_lsu_io_req_bits_uop_lrs3),
    .io_resp_bits_uop_ldst_val        (io_lsu_io_req_bits_uop_ldst_val),
    .io_resp_bits_uop_dst_rtype       (io_lsu_io_req_bits_uop_dst_rtype),
    .io_resp_bits_uop_lrs1_rtype      (io_lsu_io_req_bits_uop_lrs1_rtype),
    .io_resp_bits_uop_lrs2_rtype      (io_lsu_io_req_bits_uop_lrs2_rtype),
    .io_resp_bits_uop_frs3_en         (io_lsu_io_req_bits_uop_frs3_en),
    .io_resp_bits_uop_fp_val          (io_lsu_io_req_bits_uop_fp_val),
    .io_resp_bits_uop_fp_single       (io_lsu_io_req_bits_uop_fp_single),
    .io_resp_bits_uop_xcpt_pf_if      (io_lsu_io_req_bits_uop_xcpt_pf_if),
    .io_resp_bits_uop_xcpt_ae_if      (io_lsu_io_req_bits_uop_xcpt_ae_if),
    .io_resp_bits_uop_xcpt_ma_if      (io_lsu_io_req_bits_uop_xcpt_ma_if),
    .io_resp_bits_uop_bp_debug_if     (io_lsu_io_req_bits_uop_bp_debug_if),
    .io_resp_bits_uop_bp_xcpt_if      (io_lsu_io_req_bits_uop_bp_xcpt_if),
    .io_resp_bits_uop_debug_fsrc      (io_lsu_io_req_bits_uop_debug_fsrc),
    .io_resp_bits_uop_debug_tsrc      (io_lsu_io_req_bits_uop_debug_tsrc),
    .io_resp_bits_data                (_maddrcalc_io_resp_bits_data),
    .io_resp_bits_addr                (io_lsu_io_req_bits_addr),
    .io_resp_bits_mxcpt_valid         (io_lsu_io_req_bits_mxcpt_valid),
    .io_resp_bits_sfence_valid        (io_lsu_io_req_bits_sfence_valid),
    .io_resp_bits_sfence_bits_rs1     (io_lsu_io_req_bits_sfence_bits_rs1),
    .io_resp_bits_sfence_bits_rs2     (io_lsu_io_req_bits_sfence_bits_rs2),
    .io_resp_bits_sfence_bits_addr    (io_lsu_io_req_bits_sfence_bits_addr),
    .io_brupdate_b1_resolve_mask      (io_brupdate_b1_resolve_mask),
    .io_brupdate_b1_mispredict_mask   (io_brupdate_b1_mispredict_mask)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:388:27]
  assign io_ll_iresp_valid = io_lsu_io_iresp_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_iresp_bits_uop_rob_idx = io_lsu_io_iresp_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_iresp_bits_uop_pdst = io_lsu_io_iresp_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_iresp_bits_uop_is_amo = io_lsu_io_iresp_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_iresp_bits_uop_uses_stq = io_lsu_io_iresp_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_iresp_bits_uop_dst_rtype = io_lsu_io_iresp_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_iresp_bits_data = {1'h0, io_lsu_io_iresp_bits_data};	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :401:17]
  assign io_ll_fresp_valid = io_lsu_io_fresp_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_uopc = io_lsu_io_fresp_bits_uop_uopc;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_br_mask = io_lsu_io_fresp_bits_uop_br_mask;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_rob_idx = io_lsu_io_fresp_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_stq_idx = io_lsu_io_fresp_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_pdst = io_lsu_io_fresp_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_mem_size = io_lsu_io_fresp_bits_uop_mem_size;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_is_amo = io_lsu_io_fresp_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_uses_stq = io_lsu_io_fresp_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_dst_rtype = io_lsu_io_fresp_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_uop_fp_val = io_lsu_io_fresp_bits_uop_fp_val;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_ll_fresp_bits_data = io_lsu_io_fresp_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  assign io_lsu_io_req_bits_data = _maddrcalc_io_resp_bits_data[63:0];	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :388:27, :399:19]
endmodule

