// Generated by CIRCT firtool-1.75.0
module Arbiter3_UInt4(	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  input        io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [3:0] io_in_0_bits,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input        io_in_1_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [3:0] io_in_1_bits,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output       io_in_2_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [3:0] io_in_2_bits,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [3:0] io_out_bits	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
);

  assign io_in_2_ready = ~(io_in_0_valid | io_in_1_valid);	// @[src/main/scala/chisel3/util/Arbiter.scala:45:{68,78}, :133:7]
  assign io_out_bits = io_in_0_valid ? io_in_0_bits : io_in_1_valid ? io_in_1_bits : io_in_2_bits;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
endmodule

