// Generated by CIRCT firtool-1.75.0
module Arbiter3_BoomL1DataReadReq(	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  input         io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [3:0]  io_in_0_bits_req_0_way_en,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [11:0] io_in_0_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_in_1_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_in_1_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [3:0]  io_in_1_bits_req_0_way_en,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [11:0] io_in_1_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_in_2_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_in_2_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [11:0] io_in_2_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_in_2_bits_valid_0,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [3:0]  io_out_bits_req_0_way_en,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [11:0] io_out_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_out_bits_valid_0	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
);

  wire _io_out_valid_T = io_in_0_valid | io_in_1_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:68]
  assign io_in_1_ready = ~io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:78, :133:7]
  assign io_in_2_ready = ~_io_out_valid_T;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:{68,78}, :133:7]
  assign io_out_valid = _io_out_valid_T | io_in_2_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:68, :133:7, :154:31]
  assign io_out_bits_req_0_way_en = io_in_0_valid ? io_in_0_bits_req_0_way_en : io_in_1_valid ? io_in_1_bits_req_0_way_en : 4'hF;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :140:14, :143:15, :145:26, :147:19]
  assign io_out_bits_req_0_addr = io_in_0_valid ? io_in_0_bits_req_0_addr : io_in_1_valid ? io_in_1_bits_req_0_addr : io_in_2_bits_req_0_addr;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
  assign io_out_bits_valid_0 = io_in_0_valid | io_in_1_valid | io_in_2_bits_valid_0;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
endmodule

