// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomDuplicatedDataArray(	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
  input         io_read_0_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [3:0]  io_read_0_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [11:0] io_read_0_bits_addr,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input         io_write_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [3:0]  io_write_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [11:0] io_write_bits_addr,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [63:0] io_write_bits_data,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [63:0] io_resp_0_0,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [63:0] io_resp_0_1,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [63:0] io_resp_0_2,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [63:0] io_resp_0_3	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
);

  wire [63:0] _array_3_0_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [63:0] _array_2_0_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [63:0] _array_1_0_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [63:0] _array_0_0_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  reg  [63:0] io_resp_0_0_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [63:0] io_resp_0_1_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [63:0] io_resp_0_2_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [63:0] io_resp_0_3_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    io_resp_0_0_REG <= _array_0_0_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_1_REG <= _array_1_0_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_2_REG <= _array_2_0_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_3_REG <= _array_3_0_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    initial begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        end	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        io_resp_0_0_REG = {_RANDOM[3'h0], _RANDOM[3'h1]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_1_REG = {_RANDOM[3'h2], _RANDOM[3'h3]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_2_REG = {_RANDOM[3'h4], _RANDOM[3'h5]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_3_REG = {_RANDOM[3'h6], _RANDOM[3'h7]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  array_0_0_0 array_0_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[0] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_0_0_0_R0_data),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[0] & io_write_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_1_0_0 array_1_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[1] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_1_0_0_R0_data),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[1] & io_write_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_2_0_0 array_2_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[2] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_2_0_0_R0_data),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[2] & io_write_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_3_0_0 array_3_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[3] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_3_0_0_R0_data),
    .W0_addr (io_write_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[3] & io_write_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign io_resp_0_0 = io_resp_0_0_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_1 = io_resp_0_1_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_2 = io_resp_0_2_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_3 = io_resp_0_3_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
endmodule

