// Generated by CIRCT firtool-1.75.0
module data(	// @[generators/boom/src/main/scala/v3/ifu/bpd/bim.scala:50:26]
  input  [10:0] R0_addr,
  input         R0_en,
  input         R0_clk,
  output [7:0]  R0_data,
  input  [10:0] W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [7:0]  W0_data,
  input  [3:0]  W0_mask
);

  data_ext data_ext (	// @[generators/boom/src/main/scala/v3/ifu/bpd/bim.scala:50:26]
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .W0_mask (W0_mask)
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/bim.scala:50:26]
endmodule

