// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ICache(	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
  input         auto_master_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_master_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_master_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_master_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_master_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_master_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_master_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  input  [38:0] io_req_bits_addr,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  input  [31:0] io_s1_paddr,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  input         io_s1_kill,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  input         io_s2_kill,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  output        io_resp_valid,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  output [63:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  input         io_invalidate,	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
  output        io_perf_acquire	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
);

  wire         masterNodeOut_a_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:326:{29,46}]
  wire         readEnable;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:60]
  wire         writeEnable;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}]
  wire         readEnable_0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:60]
  wire         writeEnable_0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}]
  wire         readEnable_1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:60]
  wire         writeEnable_1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}]
  wire         readEnable_2;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:60]
  wire         wen;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}]
  wire         tag_array_MPORT_mask_3;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:156:100]
  wire         tag_array_MPORT_mask_2;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:156:100]
  wire         tag_array_MPORT_mask_1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:156:100]
  wire         tag_array_MPORT_mask_0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:156:100]
  wire         tag_array_tag_rdata_en;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:154:84]
  wire [5:0]   _tag_rdata_T;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:154:42]
  wire         io_req_ready;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:144:19]
  wire [63:0]  _dataArrayWay_3_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [63:0]  _dataArrayWay_2_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [63:0]  _dataArrayWay_1_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [63:0]  _dataArrayWay_0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [79:0]  _tag_array_RW0_rdata;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30]
  wire         _repl_way_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _repl_way_prng_io_out_1;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         s0_valid = io_req_ready & io_req_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:144:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg          s1_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:128:25]
  reg          s2_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:131:25]
  reg          s2_hit;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:132:23]
  reg          invalidated;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24]
  reg          refill_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:136:29]
  wire         refill_fire = auto_master_out_a_ready & masterNodeOut_a_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:326:{29,46}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg          s2_miss_REG;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:138:48]
  wire         s2_miss = s2_valid & ~s2_hit & ~s2_miss_REG;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:131:25, :132:23, :138:{26,29,37,40,48}]
  reg  [31:0]  refill_paddr;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:139:31]
  wire         refill_one_beat = auto_master_out_d_valid & auto_master_out_d_bits_opcode[0];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36]
  assign io_req_ready = ~refill_one_beat;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, :144:19]
  wire [26:0]  _r_beats1_decode_T = 27'hFFF << auto_master_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [8:0]   r_beats1 = auto_master_out_d_bits_opcode[0] ? ~(_r_beats1_decode_T[11:3]) : 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  reg  [8:0]   r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire [8:0]   _r_counter1_T = r_counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
  wire [8:0]   refill_cnt = r_beats1 & ~_r_counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :230:28, :234:{25,27}]
  wire         refill_done = refill_one_beat & (r_counter == 9'h1 | r_beats1 == 9'h0);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, :147:37, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{25,33,43}, :233:22]
  wire [1:0]   repl_way = {_repl_way_prng_io_out_1, _repl_way_prng_io_out_0};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:151:58, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign _tag_rdata_T = io_req_bits_addr[11:6];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:154:42]
  assign tag_array_tag_rdata_en = ~refill_done & s0_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:147:37, :154:{71,84}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign tag_array_MPORT_mask_0 = ~(|repl_way);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:151:58, :156:100]
  assign tag_array_MPORT_mask_1 = repl_way == 2'h1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:151:58, :156:100]
  assign tag_array_MPORT_mask_2 = repl_way == 2'h2;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:151:58, :156:100]
  assign tag_array_MPORT_mask_3 = &repl_way;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:151:58, :156:100]
  reg  [255:0] vb_array;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25]
  wire [255:0] _s1_vb_T_1 = vb_array >> io_s1_paddr[11:6];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25, :173:29, :175:25]
  wire         s1_tag_hit_0 = _s1_vb_T_1[0] & _tag_array_RW0_rdata[19:0] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30, :174:29, :175:25, :177:{28,35}]
  wire [255:0] _s1_vb_T_3 = vb_array >> {250'h1, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25, :173:29, :175:25]
  wire         s1_tag_hit_1 = _s1_vb_T_3[0] & _tag_array_RW0_rdata[39:20] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30, :174:29, :175:25, :177:{28,35}]
  wire [255:0] _s1_vb_T_5 = vb_array >> {250'h2, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25, :173:29, :175:25]
  wire         s1_tag_hit_2 = _s1_vb_T_5[0] & _tag_array_RW0_rdata[59:40] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30, :174:29, :175:25, :177:{28,35}]
  wire [255:0] _s1_vb_T_7 = vb_array >> {250'h3, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25, :173:29, :175:25]
  wire         s1_tag_hit_3 = _s1_vb_T_7[0] & _tag_array_RW0_rdata[79:60] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30, :174:29, :175:25, :177:{28,35}]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:179:9]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:179:9]
      if (~reset & ~({1'h0, {1'h0, s1_tag_hit_0} + {1'h0, s1_tag_hit_1}} + {1'h0, {1'h0, s1_tag_hit_2} + {1'h0, s1_tag_hit_3}} < 3'h2 | ~s1_valid)) begin	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:128:25, :177:28, :179:{9,18,31,38,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:179:9]
          $error("Assertion failed\n    at icache.scala:179 assert(PopCount(s1_tag_hit) <= 1.U || !s1_valid)\n");	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:179:9]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:179:9]
          $fatal;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:179:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign wen = refill_one_beat & ~invalidated & ~(|repl_way);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24, :142:39, :151:58, :156:100, :221:{34,37,51,63}]
  wire [8:0]   _mem_idx_T_9 = {refill_paddr[11:6], 3'h0};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:139:31, :141:32, :223:54]
  assign readEnable_2 = ~wen & s0_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:{55,60}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [63:0]  s2_dout_0_REG;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30]
  assign writeEnable_1 = refill_one_beat & ~invalidated & repl_way == 2'h1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24, :142:39, :151:58, :221:{34,37,51,63}]
  assign readEnable_1 = ~writeEnable_1 & s0_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:{55,60}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [63:0]  s2_dout_1_REG;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30]
  assign writeEnable_0 = refill_one_beat & ~invalidated & repl_way == 2'h2;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24, :142:39, :151:58, :221:{34,37,51,63}]
  assign readEnable_0 = ~writeEnable_0 & s0_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:{55,60}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [63:0]  s2_dout_2_REG;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30]
  assign writeEnable = refill_one_beat & ~invalidated & (&repl_way);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24, :142:39, :151:58, :221:{34,37,51,63}]
  assign readEnable = ~writeEnable & s0_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:{55,60}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [63:0]  s2_dout_3_REG;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30]
  reg          s2_tag_hit_0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:302:27]
  reg          s2_tag_hit_1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:302:27]
  reg          s2_tag_hit_2;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:302:27]
  reg          s2_tag_hit_3;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:302:27]
  assign masterNodeOut_a_valid = s2_miss & ~refill_valid & ~io_s2_kill;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:136:29, :138:{26,37}, :326:{29,32,46,49}]
  wire [255:0] _vb_array_T_3 = 256'h1 << {248'h0, _repl_way_prng_io_out_1, _repl_way_prng_io_out_0, refill_paddr[11:6]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:139:31, :141:32, :161:32, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
    s1_valid <= s0_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:128:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    s2_valid <= s1_valid & ~io_s1_kill;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:128:25, :131:{25,35,38}]
    s2_hit <= s1_tag_hit_0 | s1_tag_hit_1 | s1_tag_hit_2 | s1_tag_hit_3;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:130:35, :132:23, :177:28]
    invalidated <= refill_valid & (io_invalidate | invalidated);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24, :136:29, :164:24, :166:17, :337:{24,38}]
    s2_miss_REG <= refill_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:136:29, :138:48]
    if (s1_valid & ~(refill_valid | s2_miss))	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:128:25, :136:29, :138:{26,37}, :139:{54,57,72}]
      refill_paddr <= io_s1_paddr;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:139:31]
    s2_dout_0_REG <= _dataArrayWay_0_RW0_rdata;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    s2_dout_1_REG <= _dataArrayWay_1_RW0_rdata;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    s2_dout_2_REG <= _dataArrayWay_2_RW0_rdata;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    s2_dout_3_REG <= _dataArrayWay_3_RW0_rdata;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:231:30, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    s2_tag_hit_0 <= s1_tag_hit_0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:177:28, :302:27]
    s2_tag_hit_1 <= s1_tag_hit_1;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:177:28, :302:27]
    s2_tag_hit_2 <= s1_tag_hit_2;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:177:28, :302:27]
    s2_tag_hit_3 <= s1_tag_hit_3;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:177:28, :302:27]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
      refill_valid <= 1'h0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:136:29]
      r_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      vb_array <= 256'h0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25]
    end
    else begin	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
      refill_valid <= ~refill_done & (refill_fire | refill_valid);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:136:29, :147:37, :338:{22,37}, :339:{22,37}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (auto_master_out_d_valid)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
        r_counter <= r_counter == 9'h0 ? r_beats1 : _r_counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :230:28, :231:25, :236:21]
      if (io_invalidate)	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:107:14]
        vb_array <= 256'h0;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:159:25]
      else if (refill_one_beat)	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39]
        vb_array <= refill_done & ~invalidated ? vb_array | _vb_array_T_3 : ~(~vb_array | _vb_array_T_3);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:135:24, :147:37, :159:25, :161:{32,72,75}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:17];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
    initial begin	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
        end	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
        s1_valid = _RANDOM[5'h0][0];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25]
        s2_valid = _RANDOM[5'h0][1];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25, :131:25]
        s2_hit = _RANDOM[5'h0][2];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25, :132:23]
        invalidated = _RANDOM[5'h0][3];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25, :135:24]
        refill_valid = _RANDOM[5'h0][4];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25, :136:29]
        s2_miss_REG = _RANDOM[5'h0][5];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25, :138:48]
        refill_paddr = {_RANDOM[5'h0][31:6], _RANDOM[5'h1][5:0]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :128:25, :139:31]
        r_counter = _RANDOM[5'h1][14:6];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :139:31, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        vb_array = {_RANDOM[5'h1][31:15], _RANDOM[5'h2], _RANDOM[5'h3], _RANDOM[5'h4], _RANDOM[5'h5], _RANDOM[5'h6], _RANDOM[5'h7], _RANDOM[5'h8], _RANDOM[5'h9][14:0]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :139:31, :159:25]
        s2_dout_0_REG = {_RANDOM[5'h9][31:15], _RANDOM[5'hA], _RANDOM[5'hB][14:0]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :159:25, :231:30]
        s2_dout_1_REG = {_RANDOM[5'hB][31:15], _RANDOM[5'hC], _RANDOM[5'hD][14:0]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30]
        s2_dout_2_REG = {_RANDOM[5'hD][31:15], _RANDOM[5'hE], _RANDOM[5'hF][14:0]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30]
        s2_dout_3_REG = {_RANDOM[5'hF][31:15], _RANDOM[5'h10], _RANDOM[5'h11][14:0]};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30]
        s2_tag_hit_0 = _RANDOM[5'h11][15];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30, :302:27]
        s2_tag_hit_1 = _RANDOM[5'h11][16];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30, :302:27]
        s2_tag_hit_2 = _RANDOM[5'h11][17];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30, :302:27]
        s2_tag_hit_3 = _RANDOM[5'h11][18];	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30, :302:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MaxPeriodFibonacciLFSR repl_way_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock        (clock),
    .reset        (reset),
    .io_increment (refill_fire),	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_out_0     (_repl_way_prng_io_out_0),
    .io_out_1     (_repl_way_prng_io_out_1),
    .io_out_2     (/* unused */),
    .io_out_3     (/* unused */),
    .io_out_4     (/* unused */),
    .io_out_5     (/* unused */),
    .io_out_6     (/* unused */),
    .io_out_7     (/* unused */),
    .io_out_8     (/* unused */),
    .io_out_9     (/* unused */),
    .io_out_10    (/* unused */),
    .io_out_11    (/* unused */),
    .io_out_12    (/* unused */),
    .io_out_13    (/* unused */),
    .io_out_14    (/* unused */),
    .io_out_15    (/* unused */)
  );	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  tag_array_0 tag_array (	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30]
    .RW0_addr  (refill_done ? refill_paddr[11:6] : _tag_rdata_T),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:139:31, :141:32, :147:37, :153:30, :154:42, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22]
    .RW0_en    (tag_array_tag_rdata_en | refill_done),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:147:37, :153:30, :154:84, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39]
    .RW0_wdata ({4{refill_paddr[31:12]}}),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:139:31, :140:32, :153:30]
    .RW0_rdata (_tag_array_RW0_rdata),
    .RW0_wmask ({tag_array_MPORT_mask_3, tag_array_MPORT_mask_2, tag_array_MPORT_mask_1, tag_array_MPORT_mask_0})	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30, :156:100]
  );	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:153:30]
  dataArrayWay_0 dataArrayWay_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? _mem_idx_T_9 | refill_cnt : io_req_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, :218:33, :223:{24,54,81}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:25]
    .RW0_en    (readEnable_2 | wen),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:60, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39]
    .RW0_wdata (auto_master_out_d_bits_data),
    .RW0_rdata (_dataArrayWay_0_RW0_rdata)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  dataArrayWay_1 dataArrayWay_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? _mem_idx_T_9 | refill_cnt : io_req_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, :218:33, :223:{24,54,81}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:25]
    .RW0_en    (readEnable_1 | writeEnable_1),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:60, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39]
    .RW0_wdata (auto_master_out_d_bits_data),
    .RW0_rdata (_dataArrayWay_1_RW0_rdata)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  dataArrayWay_2 dataArrayWay_2 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? _mem_idx_T_9 | refill_cnt : io_req_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, :218:33, :223:{24,54,81}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:25]
    .RW0_en    (readEnable_0 | writeEnable_0),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:60, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39]
    .RW0_wdata (auto_master_out_d_bits_data),
    .RW0_rdata (_dataArrayWay_2_RW0_rdata)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  dataArrayWay_3 dataArrayWay_3 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? _mem_idx_T_9 | refill_cnt : io_req_bits_addr[11:3]),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39, :218:33, :223:{24,54,81}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:25]
    .RW0_en    (readEnable | writeEnable),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:221:{34,51}, :231:60, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:142:39]
    .RW0_wdata (auto_master_out_d_bits_data),
    .RW0_rdata (_dataArrayWay_3_RW0_rdata)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign auto_master_out_a_valid = masterNodeOut_a_valid;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :326:{29,46}]
  assign auto_master_out_a_bits_address = {refill_paddr[31:6], 6'h0};	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :139:31, :329:{31,48}]
  assign io_resp_valid = s2_valid & s2_hit;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :131:25, :132:23, :324:29]
  assign io_resp_bits_data = (s2_tag_hit_0 ? s2_dout_0_REG : 64'h0) | (s2_tag_hit_1 ? s2_dout_1_REG : 64'h0) | (s2_tag_hit_2 ? s2_dout_2_REG : 64'h0) | (s2_tag_hit_3 ? s2_dout_3_REG : 64'h0);	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, :231:30, :302:27, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_perf_acquire = refill_fire;	// @[generators/boom/src/main/scala/v3/ifu/icache.scala:103:7, src/main/scala/chisel3/util/Decoupled.scala:51:35]
endmodule

