// Generated by CIRCT firtool-1.75.0
module lo_us_1(	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
  input  [7:0] R0_addr,
  input        R0_en,
  input        R0_clk,
  output [3:0] R0_data,
  input  [7:0] W0_addr,
  input        W0_clk,
  input  [3:0] W0_data,
  input  [3:0] W0_mask
);

  hi_us_0_ext hi_us_0_ext (	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (1'h1),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .W0_mask (W0_mask)
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
endmodule

