// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue1_FetchBundle(	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input          clock,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input          reset,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  output         io_enq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_pc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_next_pc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_edge_inst_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_insts_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_insts_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_insts_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_insts_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_exp_insts_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_exp_insts_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_exp_insts_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_exp_insts_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_sfbs_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_sfbs_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_sfbs_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_sfbs_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]   io_enq_bits_sfb_masks_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]   io_enq_bits_sfb_masks_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]   io_enq_bits_sfb_masks_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]   io_enq_bits_sfb_masks_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [3:0]   io_enq_bits_sfb_dests_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [3:0]   io_enq_bits_sfb_dests_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [3:0]   io_enq_bits_sfb_dests_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [3:0]   io_enq_bits_sfb_dests_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_shadowable_mask_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_shadowable_mask_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_shadowable_mask_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_shadowable_mask_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_cfi_idx_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]   io_enq_bits_cfi_idx_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [2:0]   io_enq_bits_cfi_type,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_cfi_is_call,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_cfi_is_ret,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_cfi_npc_plus4,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_ras_top,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [3:0]   io_enq_bits_mask,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [3:0]   io_enq_bits_br_mask,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [63:0]  io_enq_bits_ghist_old_history,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_ghist_current_saw_branch_not_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_ghist_new_saw_branch_not_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_ghist_new_saw_branch_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]   io_enq_bits_ghist_ras_idx,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_lhist_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_xcpt_pf_if,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_xcpt_ae_if,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_end_half_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [15:0]  io_enq_bits_end_half_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [119:0] io_enq_bits_bpd_meta_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]   io_enq_bits_fsrc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]   io_enq_bits_tsrc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_deq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_pc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_edge_inst_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_insts_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_insts_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_insts_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_insts_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_exp_insts_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_exp_insts_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_exp_insts_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_exp_insts_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_sfbs_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_sfbs_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_sfbs_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_sfbs_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_shadowed_mask_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_shadowed_mask_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_shadowed_mask_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_shadowed_mask_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_cfi_idx_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]   io_deq_bits_cfi_idx_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [2:0]   io_deq_bits_cfi_type,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_cfi_is_call,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_cfi_is_ret,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_ras_top,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [3:0]   io_deq_bits_mask,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [3:0]   io_deq_bits_br_mask,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [63:0]  io_deq_bits_ghist_old_history,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_ghist_current_saw_branch_not_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_ghist_new_saw_branch_not_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_ghist_new_saw_branch_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]   io_deq_bits_ghist_ras_idx,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_xcpt_pf_if,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_xcpt_ae_if,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_debug_if_oh_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_debug_if_oh_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_debug_if_oh_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_debug_if_oh_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_xcpt_if_oh_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_xcpt_if_oh_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_xcpt_if_oh_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_bp_xcpt_if_oh_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [119:0] io_deq_bits_bpd_meta_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]   io_deq_bits_fsrc	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
);

  reg  [681:0] ram;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  reg          full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
  wire         io_enq_ready_0 = io_deq_ready | ~full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27, :286:{16,19}, :306:{24,39}]
  wire         do_enq = io_enq_ready_0 & io_enq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:16, :306:{24,39}]
  always @(posedge clock) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      ram <= {io_enq_bits_tsrc, io_enq_bits_fsrc, io_enq_bits_bpd_meta_0, io_enq_bits_end_half_bits, io_enq_bits_end_half_valid, 8'h0, io_enq_bits_xcpt_ae_if, io_enq_bits_xcpt_pf_if, io_enq_bits_lhist_0, io_enq_bits_ghist_ras_idx, io_enq_bits_ghist_new_saw_branch_taken, io_enq_bits_ghist_new_saw_branch_not_taken, io_enq_bits_ghist_current_saw_branch_not_taken, io_enq_bits_ghist_old_history, io_enq_bits_br_mask, io_enq_bits_mask, 4'h0, io_enq_bits_ras_top, io_enq_bits_cfi_npc_plus4, io_enq_bits_cfi_is_ret, io_enq_bits_cfi_is_call, io_enq_bits_cfi_type, io_enq_bits_cfi_idx_bits, io_enq_bits_cfi_idx_valid, 4'h0, io_enq_bits_shadowable_mask_3, io_enq_bits_shadowable_mask_2, io_enq_bits_shadowable_mask_1, io_enq_bits_shadowable_mask_0, io_enq_bits_sfb_dests_3, io_enq_bits_sfb_dests_2, io_enq_bits_sfb_dests_1, io_enq_bits_sfb_dests_0, io_enq_bits_sfb_masks_3, io_enq_bits_sfb_masks_2, io_enq_bits_sfb_masks_1, io_enq_bits_sfb_masks_0, io_enq_bits_sfbs_3, io_enq_bits_sfbs_2, io_enq_bits_sfbs_1, io_enq_bits_sfbs_0, io_enq_bits_exp_insts_3, io_enq_bits_exp_insts_2, io_enq_bits_exp_insts_1, io_enq_bits_exp_insts_0, io_enq_bits_insts_3, io_enq_bits_insts_2, io_enq_bits_insts_1, io_enq_bits_insts_0, io_enq_bits_edge_inst_0, io_enq_bits_next_pc, io_enq_bits_pc};	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14, :256:91]
    if (reset)	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      full <= 1'h0;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
    else if (~(do_enq == (io_deq_ready & full)))	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16]
      full <= do_enq;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:21];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    initial begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        for (logic [4:0] i = 5'h0; i < 5'h16; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        end	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        ram = {_RANDOM[5'h0][31:1], _RANDOM[5'h1], _RANDOM[5'h2], _RANDOM[5'h3], _RANDOM[5'h4], _RANDOM[5'h5], _RANDOM[5'h6], _RANDOM[5'h7], _RANDOM[5'h8], _RANDOM[5'h9], _RANDOM[5'hA], _RANDOM[5'hB], _RANDOM[5'hC], _RANDOM[5'hD], _RANDOM[5'hE], _RANDOM[5'hF], _RANDOM[5'h10], _RANDOM[5'h11], _RANDOM[5'h12], _RANDOM[5'h13], _RANDOM[5'h14], _RANDOM[5'h15][10:0]};	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
        full = _RANDOM[5'h0][0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = io_enq_ready_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :286:16, :306:{24,39}]
  assign io_deq_valid = full;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27]
  assign io_deq_bits_pc = ram[39:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_edge_inst_0 = ram[80];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_insts_0 = ram[112:81];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_insts_1 = ram[144:113];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_insts_2 = ram[176:145];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_insts_3 = ram[208:177];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_exp_insts_0 = ram[240:209];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_exp_insts_1 = ram[272:241];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_exp_insts_2 = ram[304:273];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_exp_insts_3 = ram[336:305];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_sfbs_0 = ram[337];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_sfbs_1 = ram[338];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_sfbs_2 = ram[339];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_sfbs_3 = ram[340];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_shadowed_mask_0 = ram[393];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_shadowed_mask_1 = ram[394];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_shadowed_mask_2 = ram[395];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_shadowed_mask_3 = ram[396];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cfi_idx_valid = ram[397];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cfi_idx_bits = ram[399:398];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cfi_type = ram[402:400];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cfi_is_call = ram[403];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_cfi_is_ret = ram[404];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_ras_top = ram[445:406];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_mask = ram[453:450];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_br_mask = ram[457:454];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_ghist_old_history = ram[521:458];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_ghist_current_saw_branch_not_taken = ram[522];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_ghist_new_saw_branch_not_taken = ram[523];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_ghist_new_saw_branch_taken = ram[524];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_ghist_ras_idx = ram[529:525];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_xcpt_pf_if = ram[531];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_xcpt_ae_if = ram[532];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_debug_if_oh_0 = ram[533];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_debug_if_oh_1 = ram[534];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_debug_if_oh_2 = ram[535];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_debug_if_oh_3 = ram[536];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_xcpt_if_oh_0 = ram[537];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_xcpt_if_oh_1 = ram[538];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_xcpt_if_oh_2 = ram[539];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bp_xcpt_if_oh_3 = ram[540];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bpd_meta_0 = ram[677:558];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_fsrc = ram[679:678];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
endmodule

