// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RenameStage_1(	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
  input        clock,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
  input        reset,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
  output       io_ren_stalls_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_kill,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_is_br,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_is_sfb,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [2:0] io_dec_uops_0_br_tag,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_ldst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_lrs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_lrs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_dec_uops_0_lrs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_0_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_0_lrs1_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_dec_uops_0_lrs2_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dec_uops_0_frs3_en,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [5:0] io_ren2_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [5:0] io_ren2_uops_0_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [5:0] io_ren2_uops_0_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [5:0] io_ren2_uops_0_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_0_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_0_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output       io_ren2_uops_0_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  output [5:0] io_ren2_uops_0_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [2:0] io_brupdate_b2_uop_br_tag,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_brupdate_b2_mispredict,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dis_fire_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_dis_ready,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_wakeups_0_valid,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_wakeups_0_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_wakeups_0_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_wakeups_1_valid,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_wakeups_1_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_wakeups_1_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_com_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_com_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_com_uops_0_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [5:0] io_com_uops_0_ldst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_com_uops_0_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input  [1:0] io_com_uops_0_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_rbk_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_rollback,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
  input        io_debug_rob_empty	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:60:14]
);

  wire       _busytable_io_busy_resps_0_prs1_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:224:25]
  wire       _busytable_io_busy_resps_0_prs2_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:224:25]
  wire       _busytable_io_busy_resps_0_prs3_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:224:25]
  wire       _freelist_io_alloc_pregs_0_valid;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24]
  wire [5:0] _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24]
  wire [5:0] _maptable_io_map_resps_0_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:214:24]
  wire [5:0] _maptable_io_map_resps_0_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:214:24]
  wire [5:0] _maptable_io_map_resps_0_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:214:24]
  wire [5:0] _maptable_io_map_resps_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:214:24]
  reg        r_uop_is_br;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg        r_uop_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg        r_uop_is_sfb;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [2:0] r_uop_br_tag;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [5:0] r_uop_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg        r_uop_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [1:0] r_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [1:0] r_uop_lrs1_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg  [1:0] r_uop_lrs2_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  reg        r_uop_frs3_en;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
  wire       _io_ren_stalls_0_T = r_uop_dst_rtype == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :240:78]
  wire       freelist_io_reqs_0 = r_uop_ldst_val & _io_ren_stalls_0_T & io_dis_fire_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :240:{52,78,88}]
  wire       ren2_br_tags_0_valid = io_dis_fire_0 & (r_uop_is_br & ~r_uop_is_sfb | r_uop_is_jalr);	// @[generators/boom/src/main/scala/v3/common/micro-op.scala:146:{33,36,45}, generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :241:43]
  wire       _rbk_valids_0_T = io_com_uops_0_dst_rtype == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:243:82]
  wire       rbk_valids_0 = io_com_uops_0_ldst_val & _rbk_valids_0_T & io_rbk_valids_0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:243:82, :244:{54,92}]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10]
      if (~reset & {~freelist_io_reqs_0, _freelist_io_alloc_pregs_0_bits} == 7'h0) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24, :240:{52,88}, :300:{10,74,77,87}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10]
          $error("Assertion failed: [rename-stage] A uop is trying to allocate the zero physical register.\n    at rename-stage.scala:300 assert (ren2_alloc_reqs zip freelist.io.alloc_pregs map {case (r,p) => !r || p.bits =/= 0.U} reduce (_&&_),\n");	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10]
      end
      if (~reset & (io_wakeups_0_valid & io_wakeups_0_bits_uop_dst_rtype != 2'h1 | io_wakeups_1_valid & io_wakeups_1_bits_uop_dst_rtype != 2'h1)) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:300:10, :317:{10,41,65,84}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:317:10]
          $error("Assertion failed: [rename] Wakeup has wrong rtype.\n    at rename-stage.scala:317 assert (!(io.wakeups.map(x => x.valid && x.bits.uop.dst_rtype =/= rtype).reduce(_||_)),\n");	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:317:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:317:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:317:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire       _GEN = io_kill | ~io_dis_ready;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
    if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
      r_uop_is_br <= io_dec_uops_0_is_br;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_is_jalr <= io_dec_uops_0_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_is_sfb <= io_dec_uops_0_is_sfb;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_br_tag <= io_dec_uops_0_br_tag;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    end
    if (freelist_io_reqs_0 & r_uop_ldst == (_GEN ? r_uop_lrs1 : io_dec_uops_0_lrs1))	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :125:14, :127:20, :129:30, :177:{77,87}, :240:{52,88}]
      r_uop_prs1 <= _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :220:24]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
      r_uop_prs1 <= _maptable_io_map_resps_0_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :214:24]
    if (freelist_io_reqs_0 & r_uop_ldst == (_GEN ? r_uop_lrs2 : io_dec_uops_0_lrs2))	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :125:14, :127:20, :129:30, :178:{77,87}, :240:{52,88}]
      r_uop_prs2 <= _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :220:24]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
      r_uop_prs2 <= _maptable_io_map_resps_0_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :214:24]
    if (freelist_io_reqs_0 & r_uop_ldst == (_GEN ? r_uop_lrs3 : io_dec_uops_0_lrs3))	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :125:14, :127:20, :129:30, :179:{77,87}, :240:{52,88}]
      r_uop_prs3 <= _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :220:24]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
      r_uop_prs3 <= _maptable_io_map_resps_0_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :214:24]
    if (freelist_io_reqs_0 & r_uop_ldst == (_GEN ? r_uop_ldst : io_dec_uops_0_ldst))	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :125:14, :127:20, :129:30, :180:{77,87}, :240:{52,88}]
      r_uop_stale_pdst <= _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :220:24]
    else if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
      r_uop_stale_pdst <= _maptable_io_map_resps_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :214:24]
    if (_GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:125:14, :127:20, :129:30]
      r_uop_ldst <= io_dec_uops_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_lrs1 <= io_dec_uops_0_lrs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_lrs2 <= io_dec_uops_0_lrs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_lrs3 <= io_dec_uops_0_lrs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_ldst_val <= io_dec_uops_0_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_dst_rtype <= io_dec_uops_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_lrs1_rtype <= io_dec_uops_0_lrs1_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_lrs2_rtype <= io_dec_uops_0_lrs2_rtype;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
      r_uop_frs3_en <= io_dec_uops_0_frs3_en;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:11];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
        end	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
        r_uop_is_br = _RANDOM[4'h4][26];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_is_jalr = _RANDOM[4'h4][27];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_is_sfb = _RANDOM[4'h4][29];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_br_tag = _RANDOM[4'h5][8:6];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_prs1 = _RANDOM[4'h7][13:8];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_prs2 = _RANDOM[4'h7][19:14];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_prs3 = _RANDOM[4'h7][25:20];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_stale_pdst = _RANDOM[4'h8][7:2];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_ldst = {_RANDOM[4'hA][31:27], _RANDOM[4'hB][0]};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_lrs1 = _RANDOM[4'hB][6:1];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_lrs2 = _RANDOM[4'hB][12:7];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_lrs3 = _RANDOM[4'hB][18:13];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_ldst_val = _RANDOM[4'hB][19];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_dst_rtype = _RANDOM[4'hB][21:20];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_lrs1_rtype = _RANDOM[4'hB][23:22];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_lrs2_rtype = _RANDOM[4'hB][25:24];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
        r_uop_frs3_en = _RANDOM[4'hB][26];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RenameMapTable_1 maptable (	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:214:24]
    .clock                     (clock),
    .reset                     (reset),
    .io_map_reqs_0_lrs1        (io_dec_uops_0_lrs1),
    .io_map_reqs_0_lrs2        (io_dec_uops_0_lrs2),
    .io_map_reqs_0_lrs3        (io_dec_uops_0_lrs3),
    .io_map_reqs_0_ldst        (io_dec_uops_0_ldst),
    .io_map_resps_0_prs1       (_maptable_io_map_resps_0_prs1),
    .io_map_resps_0_prs2       (_maptable_io_map_resps_0_prs2),
    .io_map_resps_0_prs3       (_maptable_io_map_resps_0_prs3),
    .io_map_resps_0_stale_pdst (_maptable_io_map_resps_0_stale_pdst),
    .io_remap_reqs_0_ldst      (io_rollback ? io_com_uops_0_ldst : r_uop_ldst),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :262:30]
    .io_remap_reqs_0_pdst      (io_rollback ? io_com_uops_0_stale_pdst : _freelist_io_alloc_pregs_0_bits),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24, :263:30]
    .io_remap_reqs_0_valid     (freelist_io_reqs_0 | rbk_valids_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:240:{52,88}, :244:{54,92}, :266:38]
    .io_ren_br_tags_0_valid    (ren2_br_tags_0_valid),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:241:43]
    .io_ren_br_tags_0_bits     (r_uop_br_tag),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_rollback               (io_rollback)
  );	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:214:24]
  RenameFreeList_1 freelist (	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24]
    .clock                     (clock),
    .reset                     (reset),
    .io_reqs_0                 (freelist_io_reqs_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:240:{52,88}]
    .io_alloc_pregs_0_valid    (_freelist_io_alloc_pregs_0_valid),
    .io_alloc_pregs_0_bits     (_freelist_io_alloc_pregs_0_bits),
    .io_dealloc_pregs_0_valid  (io_com_uops_0_ldst_val & _rbk_valids_0_T & io_com_valids_0 | rbk_valids_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:243:{54,82,92}, :244:{54,92}, :293:37]
    .io_dealloc_pregs_0_bits   (io_rollback ? io_com_uops_0_pdst : io_com_uops_0_stale_pdst),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:295:33]
    .io_ren_br_tags_0_valid    (ren2_br_tags_0_valid),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:241:43]
    .io_ren_br_tags_0_bits     (r_uop_br_tag),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_debug_pipeline_empty   (io_debug_rob_empty)
  );	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24]
  RenameBusyTable_1 busytable (	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:224:25]
    .clock                     (clock),
    .reset                     (reset),
    .io_ren_uops_0_pdst        (_freelist_io_alloc_pregs_0_bits),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:220:24]
    .io_ren_uops_0_prs1        (r_uop_prs1),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    .io_ren_uops_0_prs2        (r_uop_prs2),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    .io_ren_uops_0_prs3        (r_uop_prs3),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23]
    .io_busy_resps_0_prs1_busy (_busytable_io_busy_resps_0_prs1_busy),
    .io_busy_resps_0_prs2_busy (_busytable_io_busy_resps_0_prs2_busy),
    .io_busy_resps_0_prs3_busy (_busytable_io_busy_resps_0_prs3_busy),
    .io_rebusy_reqs_0          (freelist_io_reqs_0),	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:240:{52,88}]
    .io_wb_pdsts_0             (io_wakeups_0_bits_uop_pdst),
    .io_wb_pdsts_1             (io_wakeups_1_bits_uop_pdst),
    .io_wb_valids_0            (io_wakeups_0_valid),
    .io_wb_valids_1            (io_wakeups_1_valid)
  );	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:224:25]
  assign io_ren_stalls_0 = _io_ren_stalls_0_T & ~_freelist_io_alloc_pregs_0_valid;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7, :220:24, :240:78, :339:{60,63}]
  assign io_ren2_uops_0_pdst = _freelist_io_alloc_pregs_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:160:7, :220:24]
  assign io_ren2_uops_0_prs1 = r_uop_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
  assign io_ren2_uops_0_prs2 = r_uop_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
  assign io_ren2_uops_0_prs3 = r_uop_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
  assign io_ren2_uops_0_prs1_busy = r_uop_lrs1_rtype == 2'h1 & _busytable_io_busy_resps_0_prs1_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7, :224:25, :323:{37,47}]
  assign io_ren2_uops_0_prs2_busy = r_uop_lrs2_rtype == 2'h1 & _busytable_io_busy_resps_0_prs2_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7, :224:25, :324:{37,47}]
  assign io_ren2_uops_0_prs3_busy = r_uop_frs3_en & _busytable_io_busy_resps_0_prs3_busy;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7, :224:25, :325:34]
  assign io_ren2_uops_0_stale_pdst = r_uop_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-stage.scala:122:23, :160:7]
endmodule

