// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TageTable_4(	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
  input         io_f1_req_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [39:0] io_f1_req_pc,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [63:0] io_f1_req_ghist,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_0_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_0_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_0_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_1_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_1_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_1_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_2_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_2_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_2_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output        io_f3_resp_3_valid,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [2:0]  io_f3_resp_3_bits_ctr,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  output [1:0]  io_f3_resp_3_bits_u,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_mask_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_taken_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_alloc_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [2:0]  io_update_old_ctr_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [39:0] io_update_pc,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [63:0] io_update_hist,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input         io_update_u_mask_3,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_0,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_1,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_2,	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
  input  [1:0]  io_update_u_3	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:31:14]
);

  wire        update_lo_wdata_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  wire        update_hi_wdata_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  wire [2:0]  update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:155:33]
  wire        update_lo_wdata_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  wire        update_hi_wdata_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  wire [2:0]  update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:155:33]
  wire        update_lo_wdata_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  wire        update_hi_wdata_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  wire [2:0]  update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:155:33]
  wire        update_lo_wdata_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  wire        update_hi_wdata_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  wire [2:0]  update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:155:33]
  wire        lo_us_MPORT_2_data_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:8]
  wire        lo_us_MPORT_2_data_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:8]
  wire        lo_us_MPORT_2_data_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:8]
  wire        lo_us_MPORT_2_data_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:8]
  wire        hi_us_MPORT_1_data_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:8]
  wire        hi_us_MPORT_1_data_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:8]
  wire        hi_us_MPORT_1_data_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:8]
  wire        hi_us_MPORT_1_data_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:8]
  wire [12:0] table_MPORT_data_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:123:8]
  wire [12:0] table_MPORT_data_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:123:8]
  wire [12:0] table_MPORT_data_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:123:8]
  wire [12:0] table_MPORT_data_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:123:8]
  wire [51:0] _table_R0_data;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27]
  wire [3:0]  _lo_us_R0_data;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
  wire [3:0]  _hi_us_R0_data;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27]
  reg         doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28]
  reg  [6:0]  reset_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:73:26]
  wire [6:0]  _idx_history_T_2 = io_f1_req_ghist[6:0] ^ io_f1_req_ghist[13:7] ^ io_f1_req_ghist[20:14] ^ io_f1_req_ghist[27:21];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25]
  wire [6:0]  s1_hashed_idx = io_f1_req_pc[9:3] ^ {_idx_history_T_2[6:4], _idx_history_T_2[3:0] ^ io_f1_req_ghist[31:28]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25, :60:29, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
  reg  [8:0]  s2_tag;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:95:29]
  reg         io_f3_resp_0_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:104:38]
  reg  [1:0]  io_f3_resp_0_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:105:38]
  reg  [2:0]  io_f3_resp_0_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:106:38]
  reg         io_f3_resp_1_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:104:38]
  reg  [1:0]  io_f3_resp_1_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:105:38]
  reg  [2:0]  io_f3_resp_1_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:106:38]
  reg         io_f3_resp_2_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:104:38]
  reg  [1:0]  io_f3_resp_2_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:105:38]
  reg  [2:0]  io_f3_resp_2_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:106:38]
  reg         io_f3_resp_3_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:104:38]
  reg  [1:0]  io_f3_resp_3_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:105:38]
  reg  [2:0]  io_f3_resp_3_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:106:38]
  reg  [18:0] clear_u_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:28]
  wire        doing_clear_u = clear_u_ctr[10:0] == 11'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:28, :112:{34,61}]
  wire        doing_clear_u_hi = doing_clear_u & clear_u_ctr[18];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:28, :112:61, :113:{40,54}]
  wire        doing_clear_u_lo = doing_clear_u & ~(clear_u_ctr[18]);	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:28, :112:61, :113:54, :114:{40,95}]
  wire [6:0]  _idx_history_T_5 = io_update_hist[6:0] ^ io_update_hist[13:7] ^ io_update_hist[20:14] ^ io_update_hist[27:21];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25]
  wire [6:0]  update_idx = io_update_pc[9:3] ^ {_idx_history_T_5[6:4], _idx_history_T_5[3:0] ^ io_update_hist[31:28]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25, :60:29, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
  wire [8:0]  _tag_history_T_3 = io_update_hist[8:0] ^ io_update_hist[17:9] ^ io_update_hist[26:18];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25]
  wire [8:0]  update_tag = io_update_pc[18:10] ^ {_tag_history_T_3[8:5], _tag_history_T_3[4:0] ^ io_update_hist[31:27]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25, :62:{30,50}, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
  assign table_MPORT_data_0 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_0_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:50, :72:28, :123:{8,102}, :155:33]
  assign table_MPORT_data_1 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_1_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:50, :72:28, :123:{8,102}, :155:33]
  assign table_MPORT_data_2 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_2_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:50, :72:28, :123:{8,102}, :155:33]
  assign table_MPORT_data_3 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_3_ctr};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:50, :72:28, :123:{8,102}, :155:33]
  wire        _GEN = doing_reset | doing_clear_u_hi;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :113:40, :130:21]
  assign hi_us_MPORT_1_data_0 = ~_GEN & update_hi_wdata_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:{8,21}, :166:44]
  assign hi_us_MPORT_1_data_1 = ~_GEN & update_hi_wdata_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:{8,21}, :166:44]
  assign hi_us_MPORT_1_data_2 = ~_GEN & update_hi_wdata_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:{8,21}, :166:44]
  assign hi_us_MPORT_1_data_3 = ~_GEN & update_hi_wdata_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:{8,21}, :166:44]
  wire [3:0]  _GEN_0 = {io_update_u_mask_3, io_update_u_mask_2, io_update_u_mask_1, io_update_u_mask_0};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:80]
  wire        _GEN_1 = doing_reset | doing_clear_u_lo;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :114:40, :137:21]
  assign lo_us_MPORT_2_data_0 = ~_GEN_1 & update_lo_wdata_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:{8,21}, :167:44]
  assign lo_us_MPORT_2_data_1 = ~_GEN_1 & update_lo_wdata_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:{8,21}, :167:44]
  assign lo_us_MPORT_2_data_2 = ~_GEN_1 & update_lo_wdata_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:{8,21}, :167:44]
  assign lo_us_MPORT_2_data_3 = ~_GEN_1 & update_lo_wdata_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:137:{8,21}, :167:44]
  reg  [8:0]  wrbypass_tags_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29]
  reg  [8:0]  wrbypass_tags_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29]
  reg  [6:0]  wrbypass_idxs_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:142:29]
  reg  [6:0]  wrbypass_idxs_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:142:29]
  reg  [2:0]  wrbypass_0_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_0_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_0_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_0_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_1_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_1_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_1_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg  [2:0]  wrbypass_1_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29]
  reg         wrbypass_enq_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:144:33]
  wire        wrbypass_hits_0 = ~doing_reset & wrbypass_tags_0 == update_tag & wrbypass_idxs_0 == update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :62:50, :72:28, :100:83, :141:29, :142:29, :147:18, :148:{22,37}, :149:22]
  wire        wrbypass_hit = wrbypass_hits_0 | ~doing_reset & wrbypass_tags_1 == update_tag & wrbypass_idxs_1 == update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :62:50, :72:28, :100:83, :141:29, :142:29, :147:18, :148:{22,37}, :149:22, :151:48]
  wire [2:0]  _GEN_2 = wrbypass_hits_0 ? wrbypass_0_0 : wrbypass_1_0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :143:29, :147:18, :148:37]
  wire [2:0]  _GEN_3 = wrbypass_hits_0 ? wrbypass_0_1 : wrbypass_1_1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :143:29, :147:18, :148:37]
  wire [2:0]  _GEN_4 = wrbypass_hits_0 ? wrbypass_0_2 : wrbypass_1_2;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :143:29, :147:18, :148:37]
  wire [2:0]  _GEN_5 = wrbypass_hits_0 ? wrbypass_0_3 : wrbypass_1_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:67:25, :143:29, :147:18, :148:37]
  assign update_wdata_0_ctr = io_update_alloc_0 ? (io_update_taken_0 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_0 ? ((&_GEN_2) ? 3'h7 : _GEN_2 + 3'h1) : _GEN_2 == 3'h0 ? 3'h0 : _GEN_2 - 3'h1) : io_update_taken_0 ? ((&io_update_old_ctr_0) ? 3'h7 : io_update_old_ctr_0 + 3'h1) : io_update_old_ctr_0 == 3'h0 ? 3'h0 : io_update_old_ctr_0 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :151:48, :155:33, :156:10, :159:10]
  assign update_hi_wdata_0 = io_update_u_0[1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  assign update_lo_wdata_0 = io_update_u_0[0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  assign update_wdata_1_ctr = io_update_alloc_1 ? (io_update_taken_1 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_1 ? ((&_GEN_3) ? 3'h7 : _GEN_3 + 3'h1) : _GEN_3 == 3'h0 ? 3'h0 : _GEN_3 - 3'h1) : io_update_taken_1 ? ((&io_update_old_ctr_1) ? 3'h7 : io_update_old_ctr_1 + 3'h1) : io_update_old_ctr_1 == 3'h0 ? 3'h0 : io_update_old_ctr_1 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :151:48, :155:33, :156:10, :159:10]
  assign update_hi_wdata_1 = io_update_u_1[1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  assign update_lo_wdata_1 = io_update_u_1[0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  assign update_wdata_2_ctr = io_update_alloc_2 ? (io_update_taken_2 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_2 ? ((&_GEN_4) ? 3'h7 : _GEN_4 + 3'h1) : _GEN_4 == 3'h0 ? 3'h0 : _GEN_4 - 3'h1) : io_update_taken_2 ? ((&io_update_old_ctr_2) ? 3'h7 : io_update_old_ctr_2 + 3'h1) : io_update_old_ctr_2 == 3'h0 ? 3'h0 : io_update_old_ctr_2 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :151:48, :155:33, :156:10, :159:10]
  assign update_hi_wdata_2 = io_update_u_2[1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  assign update_lo_wdata_2 = io_update_u_2[0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  assign update_wdata_3_ctr = io_update_alloc_3 ? (io_update_taken_3 ? 3'h4 : 3'h3) : wrbypass_hit ? (io_update_taken_3 ? ((&_GEN_5) ? 3'h7 : _GEN_5 + 3'h1) : _GEN_5 == 3'h0 ? 3'h0 : _GEN_5 - 3'h1) : io_update_taken_3 ? ((&io_update_old_ctr_3) ? 3'h7 : io_update_old_ctr_3 + 3'h1) : io_update_old_ctr_3 == 3'h0 ? 3'h0 : io_update_old_ctr_3 - 3'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :67:{8,20,25,43}, :68:{20,25,43}, :151:48, :155:33, :156:10, :159:10]
  assign update_hi_wdata_3 = io_update_u_3[1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:166:44]
  assign update_lo_wdata_3 = io_update_u_3[0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:167:44]
  wire [8:0]  _tag_history_T_1 = io_f1_req_ghist[8:0] ^ io_f1_req_ghist[17:9] ^ io_f1_req_ghist[26:18];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25]
  wire        _GEN_6 = io_update_mask_0 | io_update_mask_1 | io_update_mask_2 | io_update_mask_3;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:170:32]
  wire        _GEN_7 = ~_GEN_6 | wrbypass_hit | wrbypass_enq_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :144:33, :151:48, :170:{32,38}, :171:39, :175:39]
  wire        _GEN_8 = ~_GEN_6 | wrbypass_hit | ~wrbypass_enq_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :144:33, :151:48, :170:{32,38}, :171:39, :175:39]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      doing_reset <= 1'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28]
      reset_idx <= 7'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:73:26]
      clear_u_ctr <= 19'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:109:28]
      wrbypass_enq_idx <= 1'h0;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:144:33]
    end
    else begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      doing_reset <= reset_idx != 7'h7F & doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :73:26, :75:{19,36,50}]
      reset_idx <= reset_idx + {6'h0, doing_reset};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :73:26, :74:26]
      clear_u_ctr <= doing_reset ? 19'h1 : clear_u_ctr + 19'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :109:28, :110:{22,36,70,85}]
      if (~_GEN_6 | wrbypass_hit) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :144:33, :151:48, :170:{32,38}, :171:39]
      end
      else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:144:33, :170:38, :171:39]
        wrbypass_enq_idx <= wrbypass_enq_idx - 1'h1;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:144:33, generators/boom/src/main/scala/v3/util/util.scala:203:14]
    end
    s2_tag <= io_f1_req_pc[18:10] ^ {_tag_history_T_1[8:5], _tag_history_T_1[4:0] ^ io_f1_req_ghist[31:27]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:53:11, :55:25, :62:{30,50}, :95:29, generators/boom/src/main/scala/v3/ifu/frontend.scala:162:35]
    io_f3_resp_0_valid_REG <= _table_R0_data[12] & _table_R0_data[11:3] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :91:27, :95:29, :97:87, :100:{60,69,80,83}, :104:38]
    io_f3_resp_0_bits_u_REG <= {_hi_us_R0_data[0], _lo_us_R0_data[0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27, :90:27, :105:{38,42}]
    io_f3_resp_0_bits_ctr_REG <= _table_R0_data[2:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27, :97:87, :106:38]
    io_f3_resp_1_valid_REG <= _table_R0_data[25] & _table_R0_data[24:16] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :91:27, :95:29, :97:87, :100:{60,69,80,83}, :104:38]
    io_f3_resp_1_bits_u_REG <= {_hi_us_R0_data[1], _lo_us_R0_data[1]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27, :90:27, :105:{38,42}]
    io_f3_resp_1_bits_ctr_REG <= _table_R0_data[15:13];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27, :97:87, :106:38]
    io_f3_resp_2_valid_REG <= _table_R0_data[38] & _table_R0_data[37:29] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :91:27, :95:29, :97:87, :100:{60,69,80,83}, :104:38]
    io_f3_resp_2_bits_u_REG <= {_hi_us_R0_data[2], _lo_us_R0_data[2]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27, :90:27, :105:{38,42}]
    io_f3_resp_2_bits_ctr_REG <= _table_R0_data[28:26];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27, :97:87, :106:38]
    io_f3_resp_3_valid_REG <= _table_R0_data[51] & _table_R0_data[50:42] == s2_tag & ~doing_reset;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :91:27, :95:29, :97:87, :100:{60,69,80,83}, :104:38]
    io_f3_resp_3_bits_u_REG <= {_hi_us_R0_data[3], _lo_us_R0_data[3]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27, :90:27, :105:{38,42}]
    io_f3_resp_3_bits_ctr_REG <= _table_R0_data[41:39];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27, :97:87, :106:38]
    if (_GEN_7) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :170:38, :171:39, :175:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :170:38, :171:39, :175:39]
      wrbypass_tags_0 <= update_tag;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:50, :141:29]
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :170:38, :171:39, :175:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :170:38, :171:39, :175:39]
      wrbypass_tags_1 <= update_tag;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:62:50, :141:29]
    if (_GEN_7) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :142:29, :170:38, :171:39, :175:39, :176:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:142:29, :170:38, :171:39, :176:39]
      wrbypass_idxs_0 <= update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :142:29]
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:141:29, :142:29, :170:38, :171:39, :175:39, :176:39]
    end
    else	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:142:29, :170:38, :171:39, :176:39]
      wrbypass_idxs_1 <= update_idx;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :142:29]
    if (_GEN_6) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:170:32]
      if (wrbypass_hit) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:151:48]
        if (wrbypass_hits_0) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:147:18, :148:37]
          wrbypass_0_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
          wrbypass_0_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
          wrbypass_0_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
          wrbypass_0_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        end
        else begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:147:18, :148:37]
          wrbypass_1_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
          wrbypass_1_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
          wrbypass_1_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
          wrbypass_1_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        end
      end
      else if (wrbypass_enq_idx) begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:144:33]
        wrbypass_1_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        wrbypass_1_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        wrbypass_1_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        wrbypass_1_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
      end
      else begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:144:33]
        wrbypass_0_0 <= update_wdata_0_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        wrbypass_0_1 <= update_wdata_1_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        wrbypass_0_2 <= update_wdata_2_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
        wrbypass_0_3 <= update_wdata_3_ctr;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:143:29, :155:33]
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    initial begin	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        end	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
        doing_reset = _RANDOM[2'h0][0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28]
        reset_idx = _RANDOM[2'h0][7:1];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :73:26]
        s2_tag = _RANDOM[2'h0][16:8];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :95:29]
        io_f3_resp_0_valid_REG = _RANDOM[2'h0][17];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :104:38]
        io_f3_resp_0_bits_u_REG = _RANDOM[2'h0][19:18];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :105:38]
        io_f3_resp_0_bits_ctr_REG = _RANDOM[2'h0][22:20];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :106:38]
        io_f3_resp_1_valid_REG = _RANDOM[2'h0][23];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :104:38]
        io_f3_resp_1_bits_u_REG = _RANDOM[2'h0][25:24];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :105:38]
        io_f3_resp_1_bits_ctr_REG = _RANDOM[2'h0][28:26];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :106:38]
        io_f3_resp_2_valid_REG = _RANDOM[2'h0][29];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :104:38]
        io_f3_resp_2_bits_u_REG = _RANDOM[2'h0][31:30];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :72:28, :105:38]
        io_f3_resp_2_bits_ctr_REG = _RANDOM[2'h1][2:0];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38]
        io_f3_resp_3_valid_REG = _RANDOM[2'h1][3];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :104:38, :106:38]
        io_f3_resp_3_bits_u_REG = _RANDOM[2'h1][5:4];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :105:38, :106:38]
        io_f3_resp_3_bits_ctr_REG = _RANDOM[2'h1][8:6];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38]
        clear_u_ctr = _RANDOM[2'h1][27:9];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38, :109:28]
        wrbypass_tags_0 = {_RANDOM[2'h1][31:28], _RANDOM[2'h2][4:0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38, :141:29]
        wrbypass_tags_1 = _RANDOM[2'h2][13:5];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :141:29]
        wrbypass_idxs_0 = _RANDOM[2'h2][20:14];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :141:29, :142:29]
        wrbypass_idxs_1 = _RANDOM[2'h2][27:21];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :141:29, :142:29]
        wrbypass_0_0 = _RANDOM[2'h2][30:28];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :141:29, :143:29]
        wrbypass_0_1 = {_RANDOM[2'h2][31], _RANDOM[2'h3][1:0]};	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :141:29, :143:29]
        wrbypass_0_2 = _RANDOM[2'h3][4:2];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29]
        wrbypass_0_3 = _RANDOM[2'h3][7:5];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29]
        wrbypass_1_0 = _RANDOM[2'h3][10:8];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29]
        wrbypass_1_1 = _RANDOM[2'h3][13:11];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29]
        wrbypass_1_2 = _RANDOM[2'h3][16:14];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29]
        wrbypass_1_3 = _RANDOM[2'h3][19:17];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29]
        wrbypass_enq_idx = _RANDOM[2'h3][20];	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :143:29, :144:33]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  hi_us_3 hi_us (	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27]
    .R0_addr (s1_hashed_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29]
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_hi_us_R0_data),
    .W0_addr (doing_reset ? reset_idx : doing_clear_u_hi ? clear_u_ctr[17:11] : update_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :72:28, :73:26, :109:28, :113:40, :115:33, :129:{8,36}]
    .W0_clk  (clock),
    .W0_data ({hi_us_MPORT_1_data_3, hi_us_MPORT_1_data_2, hi_us_MPORT_1_data_1, hi_us_MPORT_1_data_0}),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27, :130:8]
    .W0_mask (_GEN ? 4'hF : _GEN_0)	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:130:21, :131:{8,80}]
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:89:27]
  lo_us_3 lo_us (	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
    .R0_addr (s1_hashed_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29]
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_lo_us_R0_data),
    .W0_addr (doing_reset ? reset_idx : doing_clear_u_lo ? clear_u_ctr[17:11] : update_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :72:28, :73:26, :109:28, :114:40, :115:33, :136:{8,36}]
    .W0_clk  (clock),
    .W0_data ({lo_us_MPORT_2_data_3, lo_us_MPORT_2_data_2, lo_us_MPORT_2_data_1, lo_us_MPORT_2_data_0}),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27, :137:8]
    .W0_mask (_GEN_1 ? 4'hF : _GEN_0)	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:131:80, :137:21, :138:8]
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:90:27]
  table_3 table_0 (	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27]
    .R0_addr (s1_hashed_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29]
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_table_R0_data),
    .W0_addr (doing_reset ? reset_idx : update_idx),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:60:29, :72:28, :73:26, :122:8]
    .W0_clk  (clock),
    .W0_data ({table_MPORT_data_3, table_MPORT_data_2, table_MPORT_data_1, table_MPORT_data_0}),	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27, :123:8]
    .W0_mask (doing_reset ? 4'hF : {io_update_mask_3, io_update_mask_2, io_update_mask_1, io_update_mask_0})	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:72:28, :124:{8,90}]
  );	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:91:27]
  assign io_f3_resp_0_valid = io_f3_resp_0_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :104:38]
  assign io_f3_resp_0_bits_ctr = io_f3_resp_0_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38]
  assign io_f3_resp_0_bits_u = io_f3_resp_0_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :105:38]
  assign io_f3_resp_1_valid = io_f3_resp_1_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :104:38]
  assign io_f3_resp_1_bits_ctr = io_f3_resp_1_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38]
  assign io_f3_resp_1_bits_u = io_f3_resp_1_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :105:38]
  assign io_f3_resp_2_valid = io_f3_resp_2_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :104:38]
  assign io_f3_resp_2_bits_ctr = io_f3_resp_2_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38]
  assign io_f3_resp_2_bits_u = io_f3_resp_2_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :105:38]
  assign io_f3_resp_3_valid = io_f3_resp_3_valid_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :104:38]
  assign io_f3_resp_3_bits_ctr = io_f3_resp_3_bits_ctr_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :106:38]
  assign io_f3_resp_3_bits_u = io_f3_resp_3_bits_u_REG;	// @[generators/boom/src/main/scala/v3/ifu/bpd/tage.scala:24:7, :105:38]
endmodule

