// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLFIFOFixer_1(	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  output        auto_anon_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_anon_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_anon_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_anon_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_anon_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [6:0]  auto_anon_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [28:0] auto_anon_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_anon_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_anon_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_anon_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_anon_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_anon_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_anon_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_anon_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [6:0]  auto_anon_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_anon_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [6:0]  auto_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [28:0] auto_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_anon_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [6:0]  auto_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_anon_out_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire [1:0]  a_id = {auto_anon_in_a_bits_address[28], ~(auto_anon_in_a_bits_address[28])};	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:59, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire        a_noDomain = a_id == 2'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :63:29, src/main/scala/chisel3/util/Mux.scala:30:73]
  reg  [2:0]  a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire        a_first = a_first_counter == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  reg  [2:0]  d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg         flight_0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_1;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_2;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_3;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_4;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_5;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_6;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_7;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_8;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_9;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_10;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_11;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_12;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_13;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_14;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_15;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  wire        stalls_a_sel = auto_anon_in_a_bits_source[6:3] == 4'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:{10,32}]
  reg  [1:0]  stalls_id;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30]
  wire        stalls_a_sel_1 = auto_anon_in_a_bits_source[6:3] == 4'h1;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:{10,32}]
  reg  [1:0]  stalls_id_1;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30]
  wire        stall = stalls_a_sel & a_first & (flight_0 | flight_1 | flight_2 | flight_3 | flight_4 | flight_5 | flight_6 | flight_7) & (a_noDomain | stalls_id != a_id) | stalls_a_sel_1 & a_first & (flight_8 | flight_9 | flight_10 | flight_11 | flight_12 | flight_13 | flight_14 | flight_15) & (a_noDomain | stalls_id_1 != a_id);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:63:29, :79:27, :85:30, :88:{15,26,44,50,65,71}, :91:45, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire        anonIn_a_ready = auto_anon_out_a_ready & ~stall;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:91:45, :95:50, :96:33]
  wire [12:0] _a_first_beats1_decode_T = 13'h3F << auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [12:0] _d_first_beats1_decode_T = 13'h3F << auto_anon_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire        d_first_first = d_first_counter == 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  wire        _GEN = d_first_first & auto_anon_out_d_bits_opcode != 3'h6 & auto_anon_in_d_ready & auto_anon_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:{42,63}, :81:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _stalls_id_T_4 = anonIn_a_ready & auto_anon_in_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:96:33, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_0 = a_first & _stalls_id_T_4;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:80:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      a_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_first_counter <= 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      flight_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_2 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_3 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_4 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_5 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_6 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_7 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_8 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_9 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_10 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_11 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_12 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_13 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_14 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
      flight_15 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      if (_stalls_id_T_4)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        a_first_counter <= a_first ? (auto_anon_in_a_bits_opcode[2] ? 3'h0 : ~(_a_first_beats1_decode_T[5:3])) : a_first_counter - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      if (auto_anon_in_d_ready & auto_anon_out_d_valid)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        d_first_counter <= d_first_first ? (auto_anon_out_d_bits_opcode[0] ? ~(_d_first_beats1_decode_T[5:3]) : 3'h0) : d_first_counter - 3'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      flight_0 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h0) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h0 | flight_0);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, generators/rocket-chip/src/main/scala/util/package.scala:243:71, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_1 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h1) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h1 | flight_1);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_2 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h2) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h2 | flight_2);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_3 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h3) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h3 | flight_3);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_4 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h4) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h4 | flight_4);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_5 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h5) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h5 | flight_5);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_6 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h6) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h6 | flight_6);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_7 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h7) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h7 | flight_7);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_8 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h8) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h8 | flight_8);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_9 <= ~(_GEN & auto_anon_out_d_bits_source == 7'h9) & (_GEN_0 & auto_anon_in_a_bits_source == 7'h9 | flight_9);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_10 <= ~(_GEN & auto_anon_out_d_bits_source == 7'hA) & (_GEN_0 & auto_anon_in_a_bits_source == 7'hA | flight_10);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_11 <= ~(_GEN & auto_anon_out_d_bits_source == 7'hB) & (_GEN_0 & auto_anon_in_a_bits_source == 7'hB | flight_11);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_12 <= ~(_GEN & auto_anon_out_d_bits_source == 7'hC) & (_GEN_0 & auto_anon_in_a_bits_source == 7'hC | flight_12);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_13 <= ~(_GEN & auto_anon_out_d_bits_source == 7'hD) & (_GEN_0 & auto_anon_in_a_bits_source == 7'hD | flight_13);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_14 <= ~(_GEN & auto_anon_out_d_bits_source == 7'hE) & (_GEN_0 & auto_anon_in_a_bits_source == 7'hE | flight_14);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_15 <= ~(_GEN & auto_anon_out_d_bits_source == 7'hF) & (_GEN_0 & auto_anon_in_a_bits_source == 7'hF | flight_15);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    if (_stalls_id_T_4 & stalls_a_sel)	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:47, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      stalls_id <= a_id;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30, src/main/scala/chisel3/util/Mux.scala:30:73]
    if (_stalls_id_T_4 & stalls_a_sel_1)	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:47, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      stalls_id_1 <= a_id;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30, src/main/scala/chisel3/util/Mux.scala:30:73]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        end	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        a_first_counter = _RANDOM[2'h0][2:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        d_first_counter = _RANDOM[2'h0][5:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        flight_0 = _RANDOM[2'h0][6];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_1 = _RANDOM[2'h0][7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_2 = _RANDOM[2'h0][8];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_3 = _RANDOM[2'h0][9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_4 = _RANDOM[2'h0][10];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_5 = _RANDOM[2'h0][11];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_6 = _RANDOM[2'h0][12];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_7 = _RANDOM[2'h0][13];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_8 = _RANDOM[2'h0][14];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_9 = _RANDOM[2'h0][15];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_10 = _RANDOM[2'h0][16];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_11 = _RANDOM[2'h0][17];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_12 = _RANDOM[2'h0][18];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_13 = _RANDOM[2'h0][19];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_14 = _RANDOM[2'h0][20];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_15 = _RANDOM[2'h0][21];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        stalls_id = _RANDOM[2'h2][8:7];	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :85:30]
        stalls_id_1 = _RANDOM[2'h2][10:9];	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :85:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_5 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (anonIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:96:33]
    .io_in_a_valid        (auto_anon_in_a_valid),
    .io_in_a_bits_opcode  (auto_anon_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_anon_in_a_bits_param),
    .io_in_a_bits_size    (auto_anon_in_a_bits_size),
    .io_in_a_bits_source  (auto_anon_in_a_bits_source),
    .io_in_a_bits_address (auto_anon_in_a_bits_address),
    .io_in_a_bits_mask    (auto_anon_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_anon_in_a_bits_corrupt),
    .io_in_d_ready        (auto_anon_in_d_ready),
    .io_in_d_valid        (auto_anon_out_d_valid),
    .io_in_d_bits_opcode  (auto_anon_out_d_bits_opcode),
    .io_in_d_bits_size    (auto_anon_out_d_bits_size),
    .io_in_d_bits_source  (auto_anon_out_d_bits_source)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  assign auto_anon_in_a_ready = anonIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :96:33]
  assign auto_anon_in_d_valid = auto_anon_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_opcode = auto_anon_out_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_size = auto_anon_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_source = auto_anon_out_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_data = auto_anon_out_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_valid = auto_anon_in_a_valid & ~stall;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :91:45, :95:{33,50}]
  assign auto_anon_out_a_bits_opcode = auto_anon_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_param = auto_anon_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_size = auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_source = auto_anon_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_address = auto_anon_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_mask = auto_anon_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_data = auto_anon_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_corrupt = auto_anon_in_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_d_ready = auto_anon_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
endmodule

