// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLToAXI4(	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [5:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [30:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [5:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_aw_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_aw_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_aw_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [30:0] auto_out_aw_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_out_aw_bits_len,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_aw_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_out_aw_bits_burst,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_aw_bits_lock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_aw_bits_cache,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_aw_bits_prot,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_aw_bits_qos,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_aw_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [5:0]  auto_out_aw_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_w_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_w_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_out_w_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_out_w_bits_strb,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_w_bits_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_b_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_out_b_bits_resp,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_b_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [5:0]  auto_out_b_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_ar_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_ar_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_ar_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [30:0] auto_out_ar_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_out_ar_bits_len,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_ar_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_out_ar_bits_burst,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_ar_bits_lock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_ar_bits_cache,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_ar_bits_prot,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_ar_bits_qos,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_ar_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [5:0]  auto_out_ar_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_r_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_r_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_r_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_out_r_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_out_r_bits_resp,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_r_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [5:0]  auto_out_r_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_r_bits_last	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  reg              count_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg              count_6;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg              count_5;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg              count_4;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  wire             idStall_3;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:286:34]
  wire             idStall_2;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:286:34]
  reg              count_1;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg              count;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  wire             _queue_arw_deq_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             _queue_arw_deq_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [2:0]       _queue_arw_deq_q_io_deq_bits_id;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [30:0]      _queue_arw_deq_q_io_deq_bits_addr;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [7:0]       _queue_arw_deq_q_io_deq_bits_len;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [2:0]       _queue_arw_deq_q_io_deq_bits_size;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [1:0]       _queue_arw_deq_q_io_deq_bits_burst;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             _queue_arw_deq_q_io_deq_bits_lock;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0]       _queue_arw_deq_q_io_deq_bits_cache;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [2:0]       _queue_arw_deq_q_io_deq_bits_prot;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0]       _queue_arw_deq_q_io_deq_bits_qos;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0]       _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [5:0]       _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             _queue_arw_deq_q_io_deq_bits_wen;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             _nodeOut_w_deq_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [63:0][2:0] _GEN = '{3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h1, 3'h4, 3'h7, 3'h6, 3'h5, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h0, 3'h3, 3'h3, 3'h3, 3'h3, 3'h3, 3'h3, 3'h3, 3'h3, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2, 3'h2};
  wire [22:0]      _r_beats1_decode_T = 23'hFF << auto_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [4:0]       r_beats1 = auto_in_a_bits_opcode[2] ? 5'h0 : ~(_r_beats1_decode_T[7:3]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  reg  [4:0]       r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire             a_first = r_counter == 5'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  wire             a_last = r_counter == 5'h1 | r_beats1 == 5'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{25,33,43}]
  reg              doneAW;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:167:30]
  wire [25:0]      _out_arw_bits_len_T = 26'h7FF << auto_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [63:0]      _GEN_0 = {{idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {count_1}, {count_4}, {count_7}, {count_6}, {count_5}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {count}, {idStall_3}, {idStall_3}, {idStall_3}, {idStall_3}, {idStall_3}, {idStall_3}, {idStall_3}, {idStall_3}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}, {idStall_2}};	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :205:49, :272:28, :286:34]
  wire             stall = _GEN_0[auto_in_a_bits_source] & a_first;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49]
  wire             _out_w_valid_T_3 = doneAW | _queue_arw_deq_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:167:30, :206:52, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             nodeIn_a_ready = ~stall & (auto_in_a_bits_opcode[2] ? _queue_arw_deq_q_io_enq_ready : _out_w_valid_T_3 & _nodeOut_w_deq_q_io_enq_ready);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49, :206:{21,28,34,52,70}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             out_arw_valid = ~stall & auto_in_a_valid & (auto_in_a_bits_opcode[2] | ~doneAW & _nodeOut_w_deq_q_io_enq_ready);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:167:30, :205:49, :206:21, :207:{31,45,51,61,69}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  reg              r_holds_d;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:216:30]
  reg  [2:0]       b_delay;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:219:24]
  wire             r_wins = auto_out_r_valid & b_delay != 3'h7 | r_holds_d;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:216:30, :219:24, :225:{33,44,53}]
  wire             nodeOut_r_ready = auto_in_d_ready & r_wins;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :227:33]
  wire             nodeOut_b_ready = auto_in_d_ready & ~r_wins;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :228:{33,36}]
  wire             nodeIn_d_valid = r_wins ? auto_out_r_valid : auto_out_b_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :229:24]
  reg              r_first;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:234:28]
  reg              r_denied_r;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire             r_denied = r_first ? (&auto_out_r_bits_resp) : r_denied_r;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:234:28, :236:39, generators/rocket-chip/src/main/scala/util/package.scala:88:{42,63}]
  wire [2:0]       nodeIn_d_bits_opcode = {2'h0, r_wins};	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :225:53, :255:23]
  wire [3:0]       nodeIn_d_bits_size = r_wins ? auto_out_r_bits_echo_tl_state_size : auto_out_b_bits_echo_tl_state_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :255:23]
  wire [5:0]       nodeIn_d_bits_source = r_wins ? auto_out_r_bits_echo_tl_state_source : auto_out_b_bits_echo_tl_state_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :255:23]
  wire             nodeIn_d_bits_denied = r_wins ? r_denied : (|auto_out_b_bits_resp);	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :238:39, :255:23, generators/rocket-chip/src/main/scala/util/package.scala:88:42]
  wire             nodeIn_d_bits_corrupt = r_wins & ((|auto_out_r_bits_resp) | r_denied);	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :237:39, :240:96, :255:23, generators/rocket-chip/src/main/scala/util/package.scala:88:42]
  wire [2:0]       d_sel_shiftAmount = r_wins ? auto_out_r_bits_id : auto_out_b_bits_id;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :261:31]
  wire             d_last = ~r_wins | auto_out_r_bits_last;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:53, :262:23]
  wire             _inc_T_7 = _queue_arw_deq_q_io_enq_ready & out_arw_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:207:{31,45}, src/main/scala/chisel3/util/Decoupled.scala:51:35, :362:21]
  wire             inc = _GEN[auto_in_a_bits_source] == 3'h0 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _dec_T_15 = auto_in_d_ready & nodeIn_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:229:24, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec = d_sel_shiftAmount == 3'h0 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             inc_1 = _GEN[auto_in_a_bits_source] == 3'h1 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_1 = d_sel_shiftAmount == 3'h1 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [3:0]       count_2;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg              write_2;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:273:24]
  wire             inc_2 = _GEN[auto_in_a_bits_source] == 3'h2 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_2 = d_sel_shiftAmount == 3'h2 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign idStall_2 = (|count_2) & write_2 != ~(auto_in_a_bits_opcode[2]) | count_2 == 4'h8;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :273:24, :274:26, :285:50, :286:{21,34,44}]
  reg  [3:0]       count_3;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg              write_3;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:273:24]
  wire             inc_3 = _GEN[auto_in_a_bits_source] == 3'h3 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_3 = d_sel_shiftAmount == 3'h3 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign idStall_3 = (|count_3) & write_3 != ~(auto_in_a_bits_opcode[2]) | count_3 == 4'h8;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :273:24, :274:26, :285:50, :286:{21,34,44}]
  wire             inc_4 = _GEN[auto_in_a_bits_source] == 3'h4 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_4 = d_sel_shiftAmount == 3'h4 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             inc_5 = _GEN[auto_in_a_bits_source] == 3'h5 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_5 = d_sel_shiftAmount == 3'h5 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             inc_6 = _GEN[auto_in_a_bits_source] == 3'h6 & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_6 = d_sel_shiftAmount == 3'h6 & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             inc_7 = (&_GEN[auto_in_a_bits_source]) & _inc_T_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17, :260:58, :276:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             dec_7 = (&d_sel_shiftAmount) & d_last & _dec_T_15;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:261:{31,93}, :262:23, :277:{22,32}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      if (~reset & ~(~dec | count)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc | ~count)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & ~(~dec_1 | count_1)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_1 | ~count_1)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & {~dec_2, count_2} == 5'h0) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_2 | count_2 != 4'h8)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & {~dec_3, count_3} == 5'h0) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_3 | count_3 != 4'h8)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & ~(~dec_4 | count_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_4 | ~count_4)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & ~(~dec_5 | count_5)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_5 | ~count_5)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & ~(~dec_6 | count_6)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_6 | ~count_6)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
      if (~reset & ~(~dec_7 | count_7)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :277:{22,32}, :280:{16,17,22}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc_7 | ~count_7)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :280:16, :281:{16,17,22,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      r_counter <= 5'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      doneAW <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :167:30]
      r_holds_d <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :216:30]
      r_first <= 1'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :234:28]
      count <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
      count_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
      count_2 <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
      count_3 <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
      count_4 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
      count_5 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
      count_6 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
      count_7 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      if (nodeIn_a_ready & auto_in_a_valid) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:206:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        r_counter <= a_first ? r_beats1 : r_counter - 5'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :230:28, :231:25, :236:21]
        doneAW <= ~a_last;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:33, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:167:30, :168:36]
      end
      if (nodeOut_r_ready & auto_out_r_valid) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:33, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        r_holds_d <= ~auto_out_r_bits_last;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:216:30, :217:40]
        r_first <= auto_out_r_bits_last;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:234:28]
      end
      count <= count + inc - dec;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_1 <= count_1 + inc_1 - dec_1;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_2 <= count_2 + {3'h0, inc_2} - {3'h0, dec_2};	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_3 <= count_3 + {3'h0, inc_3} - {3'h0, dec_3};	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_4 <= count_4 + inc_4 - dec_4;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_5 <= count_5 + inc_5 - dec_5;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_6 <= count_6 + inc_6 - dec_6;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
      count_7 <= count_7 + inc_7 - dec_7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :276:22, :277:{22,32}, :278:{24,37}]
    end
    b_delay <= auto_out_b_valid & ~nodeOut_b_ready ? b_delay + 3'h1 : 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:219:24, :220:{25,28,42}, :221:{17,28}, :223:17, :228:33]
    if (r_first)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:234:28]
      r_denied_r <= &auto_out_r_bits_resp;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:236:39, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
    if (inc_2)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:276:22]
      write_2 <= ~(auto_in_a_bits_opcode[2]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:273:24]
    if (inc_3)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:276:22]
      write_3 <= ~(auto_in_a_bits_opcode[2]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:273:24]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        end	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        r_counter = _RANDOM[1'h0][4:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        doneAW = _RANDOM[1'h0][5];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :167:30]
        r_holds_d = _RANDOM[1'h0][6];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :216:30]
        b_delay = _RANDOM[1'h0][9:7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :219:24]
        r_first = _RANDOM[1'h0][10];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :234:28]
        r_denied_r = _RANDOM[1'h0][11];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
        count = _RANDOM[1'h0][12];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        count_1 = _RANDOM[1'h0][14];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        count_2 = _RANDOM[1'h0][19:16];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        write_2 = _RANDOM[1'h0][20];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :273:24]
        count_3 = _RANDOM[1'h0][24:21];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        write_3 = _RANDOM[1'h0][25];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :273:24]
        count_4 = _RANDOM[1'h0][26];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        count_5 = _RANDOM[1'h0][28];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        count_6 = _RANDOM[1'h0][30];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        count_7 = _RANDOM[1'h1][0];	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_4 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (nodeIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:206:28]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (nodeIn_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:229:24]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
    .io_in_d_bits_size    (nodeIn_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
    .io_in_d_bits_source  (nodeIn_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
    .io_in_d_bits_denied  (nodeIn_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
    .io_in_d_bits_corrupt (nodeIn_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  Queue1_AXI4BundleW nodeOut_w_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_nodeOut_w_deq_q_io_enq_ready),
    .io_enq_valid     (~stall & auto_in_a_valid & ~(auto_in_a_bits_opcode[2]) & _out_w_valid_T_3),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49, :206:{21,52}, :209:{29,43,54}]
    .io_enq_bits_data (auto_in_a_bits_data),
    .io_enq_bits_strb (auto_in_a_bits_mask),
    .io_enq_bits_last (a_last),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:33]
    .io_deq_ready     (auto_out_w_ready),
    .io_deq_valid     (auto_out_w_valid),
    .io_deq_bits_data (auto_out_w_bits_data),
    .io_deq_bits_strb (auto_out_w_bits_strb),
    .io_deq_bits_last (auto_out_w_bits_last)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue1_AXI4BundleARW queue_arw_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                            (clock),
    .reset                            (reset),
    .io_enq_ready                     (_queue_arw_deq_q_io_enq_ready),
    .io_enq_valid                     (out_arw_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:207:{31,45}]
    .io_enq_bits_id                   (_GEN[auto_in_a_bits_source]),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:172:17]
    .io_enq_bits_addr                 (auto_in_a_bits_address),
    .io_enq_bits_len                  (~(_out_arw_bits_len_T[10:3])),	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
    .io_enq_bits_size                 (auto_in_a_bits_size > 4'h2 ? 3'h3 : auto_in_a_bits_size[2:0]),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:175:{23,31}]
    .io_enq_bits_cache                ({auto_in_a_bits_user_amba_prot_writealloc, auto_in_a_bits_user_amba_prot_readalloc, auto_in_a_bits_user_amba_prot_modifiable, auto_in_a_bits_user_amba_prot_bufferable}),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:202:25]
    .io_enq_bits_prot                 ({auto_in_a_bits_user_amba_prot_fetch, ~auto_in_a_bits_user_amba_prot_secure, auto_in_a_bits_user_amba_prot_privileged}),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:195:20, :201:25]
    .io_enq_bits_echo_tl_state_size   (auto_in_a_bits_size),
    .io_enq_bits_echo_tl_state_source (auto_in_a_bits_source),
    .io_enq_bits_wen                  (~(auto_in_a_bits_opcode[2])),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}]
    .io_deq_ready                     (_queue_arw_deq_q_io_deq_bits_wen ? auto_out_aw_ready : auto_out_ar_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:163:29, src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_deq_valid                     (_queue_arw_deq_q_io_deq_valid),
    .io_deq_bits_id                   (_queue_arw_deq_q_io_deq_bits_id),
    .io_deq_bits_addr                 (_queue_arw_deq_q_io_deq_bits_addr),
    .io_deq_bits_len                  (_queue_arw_deq_q_io_deq_bits_len),
    .io_deq_bits_size                 (_queue_arw_deq_q_io_deq_bits_size),
    .io_deq_bits_burst                (_queue_arw_deq_q_io_deq_bits_burst),
    .io_deq_bits_lock                 (_queue_arw_deq_q_io_deq_bits_lock),
    .io_deq_bits_cache                (_queue_arw_deq_q_io_deq_bits_cache),
    .io_deq_bits_prot                 (_queue_arw_deq_q_io_deq_bits_prot),
    .io_deq_bits_qos                  (_queue_arw_deq_q_io_deq_bits_qos),
    .io_deq_bits_echo_tl_state_size   (_queue_arw_deq_q_io_deq_bits_echo_tl_state_size),
    .io_deq_bits_echo_tl_state_source (_queue_arw_deq_q_io_deq_bits_echo_tl_state_source),
    .io_deq_bits_wen                  (_queue_arw_deq_q_io_deq_bits_wen)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_in_a_ready = nodeIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :206:28]
  assign auto_in_d_valid = nodeIn_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :229:24]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_size = nodeIn_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_source = nodeIn_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_denied = nodeIn_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_data = auto_out_r_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  assign auto_in_d_bits_corrupt = nodeIn_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_out_aw_valid = _queue_arw_deq_q_io_deq_valid & _queue_arw_deq_q_io_deq_bits_wen;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :162:39, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_id = _queue_arw_deq_q_io_deq_bits_id;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_addr = _queue_arw_deq_q_io_deq_bits_addr;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_len = _queue_arw_deq_q_io_deq_bits_len;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_size = _queue_arw_deq_q_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_burst = _queue_arw_deq_q_io_deq_bits_burst;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_lock = _queue_arw_deq_q_io_deq_bits_lock;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_cache = _queue_arw_deq_q_io_deq_bits_cache;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_prot = _queue_arw_deq_q_io_deq_bits_prot;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_qos = _queue_arw_deq_q_io_deq_bits_qos;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_echo_tl_state_size = _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_echo_tl_state_source = _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_b_ready = nodeOut_b_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :228:33]
  assign auto_out_ar_valid = _queue_arw_deq_q_io_deq_valid & ~_queue_arw_deq_q_io_deq_bits_wen;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :161:{39,42}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_id = _queue_arw_deq_q_io_deq_bits_id;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_addr = _queue_arw_deq_q_io_deq_bits_addr;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_len = _queue_arw_deq_q_io_deq_bits_len;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_size = _queue_arw_deq_q_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_burst = _queue_arw_deq_q_io_deq_bits_burst;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_lock = _queue_arw_deq_q_io_deq_bits_lock;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_cache = _queue_arw_deq_q_io_deq_bits_cache;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_prot = _queue_arw_deq_q_io_deq_bits_prot;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_qos = _queue_arw_deq_q_io_deq_bits_qos;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_echo_tl_state_size = _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_echo_tl_state_source = _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_r_ready = nodeOut_r_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :227:33]
endmodule

