// Generated by CIRCT firtool-1.75.0
module Zynq7CGHarness(
  input         CLK100MHZ,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Zynq7CGShell.scala:10:21]
  input         ck_rst,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Zynq7CGShell.scala:11:21]
  input         axi4_mem_0_aw_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_aw_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [3:0]  axi4_mem_0_aw_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [31:0] axi4_mem_0_aw_bits_addr,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [7:0]  axi4_mem_0_aw_bits_len,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [2:0]  axi4_mem_0_aw_bits_size,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [1:0]  axi4_mem_0_aw_bits_burst,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_aw_bits_lock,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [3:0]  axi4_mem_0_aw_bits_cache,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [2:0]  axi4_mem_0_aw_bits_prot,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [3:0]  axi4_mem_0_aw_bits_qos,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input         axi4_mem_0_w_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_w_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [63:0] axi4_mem_0_w_bits_data,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [7:0]  axi4_mem_0_w_bits_strb,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_w_bits_last,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_b_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input         axi4_mem_0_b_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input  [3:0]  axi4_mem_0_b_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input  [1:0]  axi4_mem_0_b_bits_resp,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input         axi4_mem_0_ar_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_ar_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [3:0]  axi4_mem_0_ar_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [31:0] axi4_mem_0_ar_bits_addr,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [7:0]  axi4_mem_0_ar_bits_len,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [2:0]  axi4_mem_0_ar_bits_size,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [1:0]  axi4_mem_0_ar_bits_burst,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_ar_bits_lock,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [3:0]  axi4_mem_0_ar_bits_cache,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [2:0]  axi4_mem_0_ar_bits_prot,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output [3:0]  axi4_mem_0_ar_bits_qos,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  output        axi4_mem_0_r_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input         axi4_mem_0_r_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input  [3:0]  axi4_mem_0_r_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input  [63:0] axi4_mem_0_r_bits_data,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input  [1:0]  axi4_mem_0_r_bits_resp,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input         axi4_mem_0_r_bits_last,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:14:25]
  input         axi4_mmio_0_aw_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_aw_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [3:0]  axi4_mmio_0_aw_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [30:0] axi4_mmio_0_aw_bits_addr,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [7:0]  axi4_mmio_0_aw_bits_len,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [2:0]  axi4_mmio_0_aw_bits_size,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [1:0]  axi4_mmio_0_aw_bits_burst,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_aw_bits_lock,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [3:0]  axi4_mmio_0_aw_bits_cache,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [2:0]  axi4_mmio_0_aw_bits_prot,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [3:0]  axi4_mmio_0_aw_bits_qos,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input         axi4_mmio_0_w_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_w_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [63:0] axi4_mmio_0_w_bits_data,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [7:0]  axi4_mmio_0_w_bits_strb,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_w_bits_last,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_b_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input         axi4_mmio_0_b_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input  [3:0]  axi4_mmio_0_b_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input  [1:0]  axi4_mmio_0_b_bits_resp,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input         axi4_mmio_0_ar_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_ar_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [3:0]  axi4_mmio_0_ar_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [30:0] axi4_mmio_0_ar_bits_addr,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [7:0]  axi4_mmio_0_ar_bits_len,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [2:0]  axi4_mmio_0_ar_bits_size,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [1:0]  axi4_mmio_0_ar_bits_burst,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_ar_bits_lock,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [3:0]  axi4_mmio_0_ar_bits_cache,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [2:0]  axi4_mmio_0_ar_bits_prot,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output [3:0]  axi4_mmio_0_ar_bits_qos,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  output        axi4_mmio_0_r_ready,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input         axi4_mmio_0_r_valid,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input  [3:0]  axi4_mmio_0_r_bits_id,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input  [63:0] axi4_mmio_0_r_bits_data,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input  [1:0]  axi4_mmio_0_r_bits_resp,	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
  input         axi4_mmio_0_r_bits_last	// @[fpga/src/main/scala/zynq7cg/HarnessBinders.scala:21:26]
);

  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .uart_0_txd                     (/* unused */),
    .uart_0_rxd                     (1'h1),
    .axi4_fbus_0_clock              (/* unused */),
    .axi4_fbus_0_bits_aw_ready      (/* unused */),
    .axi4_fbus_0_bits_aw_valid      (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_aw_bits_id    (8'h0),
    .axi4_fbus_0_bits_aw_bits_addr  (32'h0),
    .axi4_fbus_0_bits_aw_bits_len   (8'h0),
    .axi4_fbus_0_bits_aw_bits_size  (3'h0),
    .axi4_fbus_0_bits_aw_bits_burst (2'h0),
    .axi4_fbus_0_bits_aw_bits_lock  (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_aw_bits_cache (4'h0),
    .axi4_fbus_0_bits_aw_bits_prot  (3'h0),
    .axi4_fbus_0_bits_aw_bits_qos   (4'h0),
    .axi4_fbus_0_bits_w_ready       (/* unused */),
    .axi4_fbus_0_bits_w_valid       (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_w_bits_data   (64'h0),
    .axi4_fbus_0_bits_w_bits_strb   (8'h0),
    .axi4_fbus_0_bits_w_bits_last   (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_b_ready       (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_b_valid       (/* unused */),
    .axi4_fbus_0_bits_b_bits_id     (/* unused */),
    .axi4_fbus_0_bits_b_bits_resp   (/* unused */),
    .axi4_fbus_0_bits_ar_ready      (/* unused */),
    .axi4_fbus_0_bits_ar_valid      (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_ar_bits_id    (8'h0),
    .axi4_fbus_0_bits_ar_bits_addr  (32'h0),
    .axi4_fbus_0_bits_ar_bits_len   (8'h0),
    .axi4_fbus_0_bits_ar_bits_size  (3'h0),
    .axi4_fbus_0_bits_ar_bits_burst (2'h0),
    .axi4_fbus_0_bits_ar_bits_lock  (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_ar_bits_cache (4'h0),
    .axi4_fbus_0_bits_ar_bits_prot  (3'h0),
    .axi4_fbus_0_bits_ar_bits_qos   (4'h0),
    .axi4_fbus_0_bits_r_ready       (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_fbus_0_bits_r_valid       (/* unused */),
    .axi4_fbus_0_bits_r_bits_id     (/* unused */),
    .axi4_fbus_0_bits_r_bits_data   (/* unused */),
    .axi4_fbus_0_bits_r_bits_resp   (/* unused */),
    .axi4_fbus_0_bits_r_bits_last   (/* unused */),
    .axi4_mem_0_clock               (/* unused */),
    .axi4_mem_0_bits_aw_ready       (axi4_mem_0_aw_ready),
    .axi4_mem_0_bits_aw_valid       (axi4_mem_0_aw_valid),
    .axi4_mem_0_bits_aw_bits_id     (axi4_mem_0_aw_bits_id),
    .axi4_mem_0_bits_aw_bits_addr   (axi4_mem_0_aw_bits_addr),
    .axi4_mem_0_bits_aw_bits_len    (axi4_mem_0_aw_bits_len),
    .axi4_mem_0_bits_aw_bits_size   (axi4_mem_0_aw_bits_size),
    .axi4_mem_0_bits_aw_bits_burst  (axi4_mem_0_aw_bits_burst),
    .axi4_mem_0_bits_aw_bits_lock   (axi4_mem_0_aw_bits_lock),
    .axi4_mem_0_bits_aw_bits_cache  (axi4_mem_0_aw_bits_cache),
    .axi4_mem_0_bits_aw_bits_prot   (axi4_mem_0_aw_bits_prot),
    .axi4_mem_0_bits_aw_bits_qos    (axi4_mem_0_aw_bits_qos),
    .axi4_mem_0_bits_w_ready        (axi4_mem_0_w_ready),
    .axi4_mem_0_bits_w_valid        (axi4_mem_0_w_valid),
    .axi4_mem_0_bits_w_bits_data    (axi4_mem_0_w_bits_data),
    .axi4_mem_0_bits_w_bits_strb    (axi4_mem_0_w_bits_strb),
    .axi4_mem_0_bits_w_bits_last    (axi4_mem_0_w_bits_last),
    .axi4_mem_0_bits_b_ready        (axi4_mem_0_b_ready),
    .axi4_mem_0_bits_b_valid        (axi4_mem_0_b_valid),
    .axi4_mem_0_bits_b_bits_id      (axi4_mem_0_b_bits_id),
    .axi4_mem_0_bits_b_bits_resp    (axi4_mem_0_b_bits_resp),
    .axi4_mem_0_bits_ar_ready       (axi4_mem_0_ar_ready),
    .axi4_mem_0_bits_ar_valid       (axi4_mem_0_ar_valid),
    .axi4_mem_0_bits_ar_bits_id     (axi4_mem_0_ar_bits_id),
    .axi4_mem_0_bits_ar_bits_addr   (axi4_mem_0_ar_bits_addr),
    .axi4_mem_0_bits_ar_bits_len    (axi4_mem_0_ar_bits_len),
    .axi4_mem_0_bits_ar_bits_size   (axi4_mem_0_ar_bits_size),
    .axi4_mem_0_bits_ar_bits_burst  (axi4_mem_0_ar_bits_burst),
    .axi4_mem_0_bits_ar_bits_lock   (axi4_mem_0_ar_bits_lock),
    .axi4_mem_0_bits_ar_bits_cache  (axi4_mem_0_ar_bits_cache),
    .axi4_mem_0_bits_ar_bits_prot   (axi4_mem_0_ar_bits_prot),
    .axi4_mem_0_bits_ar_bits_qos    (axi4_mem_0_ar_bits_qos),
    .axi4_mem_0_bits_r_ready        (axi4_mem_0_r_ready),
    .axi4_mem_0_bits_r_valid        (axi4_mem_0_r_valid),
    .axi4_mem_0_bits_r_bits_id      (axi4_mem_0_r_bits_id),
    .axi4_mem_0_bits_r_bits_data    (axi4_mem_0_r_bits_data),
    .axi4_mem_0_bits_r_bits_resp    (axi4_mem_0_r_bits_resp),
    .axi4_mem_0_bits_r_bits_last    (axi4_mem_0_r_bits_last),
    .custom_boot                    (1'h1),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .jtag_TCK                       (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .jtag_TMS                       (1'h1),
    .jtag_TDI                       (1'h0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .jtag_TDO                       (/* unused */),
    .jtag_reset                     (1'h1),
    .axi4_mmio_0_clock              (/* unused */),
    .axi4_mmio_0_bits_aw_ready      (axi4_mmio_0_aw_ready),
    .axi4_mmio_0_bits_aw_valid      (axi4_mmio_0_aw_valid),
    .axi4_mmio_0_bits_aw_bits_id    (axi4_mmio_0_aw_bits_id),
    .axi4_mmio_0_bits_aw_bits_addr  (axi4_mmio_0_aw_bits_addr),
    .axi4_mmio_0_bits_aw_bits_len   (axi4_mmio_0_aw_bits_len),
    .axi4_mmio_0_bits_aw_bits_size  (axi4_mmio_0_aw_bits_size),
    .axi4_mmio_0_bits_aw_bits_burst (axi4_mmio_0_aw_bits_burst),
    .axi4_mmio_0_bits_aw_bits_lock  (axi4_mmio_0_aw_bits_lock),
    .axi4_mmio_0_bits_aw_bits_cache (axi4_mmio_0_aw_bits_cache),
    .axi4_mmio_0_bits_aw_bits_prot  (axi4_mmio_0_aw_bits_prot),
    .axi4_mmio_0_bits_aw_bits_qos   (axi4_mmio_0_aw_bits_qos),
    .axi4_mmio_0_bits_w_ready       (axi4_mmio_0_w_ready),
    .axi4_mmio_0_bits_w_valid       (axi4_mmio_0_w_valid),
    .axi4_mmio_0_bits_w_bits_data   (axi4_mmio_0_w_bits_data),
    .axi4_mmio_0_bits_w_bits_strb   (axi4_mmio_0_w_bits_strb),
    .axi4_mmio_0_bits_w_bits_last   (axi4_mmio_0_w_bits_last),
    .axi4_mmio_0_bits_b_ready       (axi4_mmio_0_b_ready),
    .axi4_mmio_0_bits_b_valid       (axi4_mmio_0_b_valid),
    .axi4_mmio_0_bits_b_bits_id     (axi4_mmio_0_b_bits_id),
    .axi4_mmio_0_bits_b_bits_resp   (axi4_mmio_0_b_bits_resp),
    .axi4_mmio_0_bits_ar_ready      (axi4_mmio_0_ar_ready),
    .axi4_mmio_0_bits_ar_valid      (axi4_mmio_0_ar_valid),
    .axi4_mmio_0_bits_ar_bits_id    (axi4_mmio_0_ar_bits_id),
    .axi4_mmio_0_bits_ar_bits_addr  (axi4_mmio_0_ar_bits_addr),
    .axi4_mmio_0_bits_ar_bits_len   (axi4_mmio_0_ar_bits_len),
    .axi4_mmio_0_bits_ar_bits_size  (axi4_mmio_0_ar_bits_size),
    .axi4_mmio_0_bits_ar_bits_burst (axi4_mmio_0_ar_bits_burst),
    .axi4_mmio_0_bits_ar_bits_lock  (axi4_mmio_0_ar_bits_lock),
    .axi4_mmio_0_bits_ar_bits_cache (axi4_mmio_0_ar_bits_cache),
    .axi4_mmio_0_bits_ar_bits_prot  (axi4_mmio_0_ar_bits_prot),
    .axi4_mmio_0_bits_ar_bits_qos   (axi4_mmio_0_ar_bits_qos),
    .axi4_mmio_0_bits_r_ready       (axi4_mmio_0_r_ready),
    .axi4_mmio_0_bits_r_valid       (axi4_mmio_0_r_valid),
    .axi4_mmio_0_bits_r_bits_id     (axi4_mmio_0_r_bits_id),
    .axi4_mmio_0_bits_r_bits_data   (axi4_mmio_0_r_bits_data),
    .axi4_mmio_0_bits_r_bits_resp   (axi4_mmio_0_r_bits_resp),
    .axi4_mmio_0_bits_r_bits_last   (axi4_mmio_0_r_bits_last),
    .reset_io                       (~ck_rst),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Zynq7CGShell.scala:34:19]
    .clock_uncore                   (CLK100MHZ),
    .clock_tap                      (/* unused */)
  );	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  ResetCatchAndSync_d3_Zynq7CGHarness_UNIQUIFIED harnessBinderReset_catcher(	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (CLK100MHZ),
    .reset         (~ck_rst),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Zynq7CGShell.scala:34:19]
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
endmodule

