// Generated by CIRCT firtool-1.75.0
module DCacheDataArray(	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:47:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:47:7]
  input         io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [13:0] io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input         io_req_bits_write,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [63:0] io_req_bits_wdata,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [1:0]  io_req_bits_wordMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [3:0]  io_req_bits_eccMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  output [63:0] io_resp_0	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
);

  wire        rockettile_dcache_data_arrays_1_rdata_data_1_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:75:39]
  wire        rockettile_dcache_data_arrays_1_rdata_MPORT_1_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17]
  wire        rockettile_dcache_data_arrays_0_rdata_data_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:75:39]
  wire        rockettile_dcache_data_arrays_0_rdata_MPORT_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17]
  wire [31:0] _rockettile_dcache_data_arrays_1_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [31:0] _rockettile_dcache_data_arrays_0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire        rdata_valid = io_req_valid & io_req_bits_wordMask[0];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:69:{30,83}]
  assign rockettile_dcache_data_arrays_0_rdata_MPORT_en = rdata_valid & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:69:30, :70:17]
  assign rockettile_dcache_data_arrays_0_rdata_data_en = rdata_valid & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:69:30, :75:{39,42}]
  wire        rdata_valid_1 = io_req_valid & io_req_bits_wordMask[1];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:69:{30,83}]
  assign rockettile_dcache_data_arrays_1_rdata_MPORT_1_en = rdata_valid_1 & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:69:30, :70:17]
  assign rockettile_dcache_data_arrays_1_rdata_data_1_en = rdata_valid_1 & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:69:30, :75:{39,42}]
  rockettile_dcache_data_arrays_0 rockettile_dcache_data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[13:3]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:57:31]
    .RW0_en    (rockettile_dcache_data_arrays_0_rdata_data_en | rockettile_dcache_data_arrays_0_rdata_MPORT_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17, :75:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata (io_req_bits_wdata[31:0]),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_0_RW0_rdata),
    .RW0_wmask (io_req_bits_eccMask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  rockettile_dcache_data_arrays_1 rockettile_dcache_data_arrays_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[13:3]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:57:31]
    .RW0_en    (rockettile_dcache_data_arrays_1_rdata_data_1_en | rockettile_dcache_data_arrays_1_rdata_MPORT_1_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17, :75:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata (io_req_bits_wdata[63:32]),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_1_RW0_rdata),
    .RW0_wmask (io_req_bits_eccMask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign io_resp_0 = {_rockettile_dcache_data_arrays_1_RW0_rdata, _rockettile_dcache_data_arrays_0_RW0_rdata};	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:47:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
endmodule

