// Generated by CIRCT firtool-1.75.0
module DCacheDataArray(	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:47:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:47:7]
  input         io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [11:0] io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input         io_req_bits_write,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [63:0] io_req_bits_wdata,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  input  [7:0]  io_req_bits_eccMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
  output [63:0] io_resp_0	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:48:14]
);

  wire rockettile_dcache_data_arrays_0_rdata_data_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:75:39]
  wire rockettile_dcache_data_arrays_0_rdata_MPORT_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17]
  assign rockettile_dcache_data_arrays_0_rdata_MPORT_en = io_req_valid & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17]
  assign rockettile_dcache_data_arrays_0_rdata_data_en = io_req_valid & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:75:{39,42}]
  rockettile_dcache_data_arrays_0 rockettile_dcache_data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:57:31]
    .RW0_en    (rockettile_dcache_data_arrays_0_rdata_data_en | rockettile_dcache_data_arrays_0_rdata_MPORT_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:70:17, :75:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata (io_req_bits_wdata),
    .RW0_rdata (io_resp_0),
    .RW0_wmask (io_req_bits_eccMask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
endmodule

