// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module rf_31x32(	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
  input  [4:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [31:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
  input         R1_clk,
  output [31:0] R1_data,
  input  [4:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:30];	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
  always @(posedge W0_clk) begin	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
    if (W0_en & 1'h1)	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
      Memory[W0_addr] <= W0_data;	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
    reg [31:0] _RANDOM_MEM;	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
    initial begin	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
      `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
        for (logic [4:0] i = 5'h0; i < 5'h1F; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
          Memory[i] = _RANDOM_MEM;	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// @[generators/rocket-chip/src/main/scala/rocket/RocketCore.scala:1349:15]
endmodule

