// Generated by CIRCT firtool-1.75.0
module RocketALU(	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:83:7]
  input  [4:0]  io_fn,	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:72:14]
  input  [31:0] io_in2,	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:72:14]
  input  [31:0] io_in1,	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:72:14]
  output [31:0] io_out,	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:72:14]
  output [31:0] io_adder_out,	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:72:14]
  output        io_cmp_out	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:72:14]
);

  wire [31:0] in2_inv = {32{io_fn[3]}} ^ io_in2;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:58:29, :87:20]
  wire [31:0] in1_xor_in2 = io_in1 ^ in2_inv;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:87:20, :88:28]
  wire [31:0] _io_adder_out_T_3 = io_in1 + in2_inv + {31'h0, io_fn[3]};	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:58:29, :87:20, :90:{26,36}]
  wire        slt = io_in1[31] == io_in2[31] ? _io_adder_out_T_3[31] : io_fn[1] ? io_in2[31] : io_in1[31];	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:61:35, :90:{26,36}, :94:{8,15,24,34,56}, :95:8]
  wire        _shout_T = io_fn == 5'h5;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _shout_T_1 = io_fn == 5'hB;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        _bext_mask_T = io_fn == 5'h13;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [18:0] _GEN = {io_in1[5:4], io_in1[7:6], io_in1[9:8], io_in1[11:10], io_in1[13:12], io_in1[15:14], io_in1[17:16], io_in1[19:18], io_in1[21:20], io_in1[23]} & 19'h55555;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:108:46]
  wire [31:0] shin = _shout_T | _shout_T_1 | io_fn == 5'h12 | _bext_mask_T ? io_in1 : {io_in1[0], io_in1[1], io_in1[2], io_in1[3], io_in1[4], _GEN[18:15] | {io_in1[7:6], io_in1[9:8]} & 4'h5, io_in1[9], _GEN[13] | io_in1[10], io_in1[11], io_in1[12], _GEN[10:7] | {io_in1[15:14], io_in1[17:16]} & 4'h5, io_in1[17], _GEN[5] | io_in1[18], io_in1[19], io_in1[20], {_GEN[2:0], 1'h0} | {io_in1[23:22], io_in1[25:24]} & 4'h5, io_in1[25], io_in1[26], io_in1[27], io_in1[28], io_in1[29], io_in1[30], io_in1[31]};	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:108:{17,46}, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59]
  wire [32:0] _shout_r_T_5 = $signed($signed({io_fn[3] & shin[31], shin}) >>> io_in2[4:0]);	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:58:29, :100:28, :108:17, :109:{21,35,41,64}]
  wire [18:0] _GEN_0 = {_shout_r_T_5[5:4], _shout_r_T_5[7:6], _shout_r_T_5[9:8], _shout_r_T_5[11:10], _shout_r_T_5[13:12], _shout_r_T_5[15:14], _shout_r_T_5[17:16], _shout_r_T_5[19:18], _shout_r_T_5[21:20], _shout_r_T_5[23]} & 19'h55555;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:109:{64,73}, :110:24]
  wire        _logic_T_8 = io_fn == 5'h6;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:121:45]
  wire        _logic_T_11 = io_fn == 5'h19;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:121:64]
  assign io_out = io_fn == 5'hA | io_fn == 5'h0 ? _io_adder_out_T_3 : {31'h0, io_fn > 5'hB & ~(io_fn[4]) & slt} | (io_fn == 5'h4 | _logic_T_8 | _logic_T_11 | io_fn == 5'h1A ? in1_xor_in2 : 32'h0) | (_logic_T_8 | io_fn == 5'h7 | _logic_T_11 | io_fn == 5'h18 ? io_in1 & in2_inv : 32'h0) | (_shout_T | _shout_T_1 | _bext_mask_T ? _shout_r_T_5[31:0] : 32'h0) | (io_fn == 5'h1 ? {_shout_r_T_5[0], _shout_r_T_5[1], _shout_r_T_5[2], _shout_r_T_5[3], _shout_r_T_5[4], _GEN_0[18:15] | {_shout_r_T_5[7:6], _shout_r_T_5[9:8]} & 4'h5, _shout_r_T_5[9], _GEN_0[13] | _shout_r_T_5[10], _shout_r_T_5[11], _shout_r_T_5[12], _GEN_0[10:7] | {_shout_r_T_5[15:14], _shout_r_T_5[17:16]} & 4'h5, _shout_r_T_5[17], _GEN_0[5] | _shout_r_T_5[18], _shout_r_T_5[19], _shout_r_T_5[20], {_GEN_0[2:0], 1'h0} | {_shout_r_T_5[23:22], _shout_r_T_5[25:24]} & 4'h5, _shout_r_T_5[25], _shout_r_T_5[26], _shout_r_T_5[27], _shout_r_T_5[28], _shout_r_T_5[29], _shout_r_T_5[30], _shout_r_T_5[31]} : 32'h0);	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:59:{31,41,48}, :83:7, :87:20, :88:28, :89:28, :90:{26,36}, :94:8, :109:{64,73}, :110:24, :111:{18,35,55,91}, :112:{18,25}, :121:{18,25,36,45,55,64,75,84,115}, :122:{18,35,44,55,75,84}, :125:{36,44,52}, :163:47, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  assign io_adder_out = _io_adder_out_T_3;	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:83:7, :90:{26,36}]
  assign io_cmp_out = io_fn[0] ^ (io_fn[3] ? slt : in1_xor_in2 == 32'h0);	// @[generators/rocket-chip/src/main/scala/rocket/ALU.scala:58:29, :62:35, :83:7, :88:28, :94:8, :96:{36,41,68}]
endmodule

