// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLMonitor_54(	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        clock,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        reset,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        io_in_a_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_a_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [1:0]  io_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [10:0] io_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [16:0] io_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [7:0]  io_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_d_ready,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_d_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [1:0]  io_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [10:0] io_in_d_bits_source	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
);

  wire [31:0]    _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire           a_first_done = io_in_a_ready & io_in_a_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg            a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg  [2:0]     opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
  reg  [2:0]     param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
  reg  [1:0]     size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:389:22]
  reg  [10:0]    source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:390:22]
  reg  [16:0]    address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:391:22]
  reg            d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg  [1:0]     size_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
  reg  [10:0]    source_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:541:22]
  reg  [1039:0]  inflight;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27]
  reg  [4159:0]  inflight_opcodes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35]
  reg  [4159:0]  inflight_sizes;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33]
  reg            a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg            d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire           _GEN = a_first_done & ~a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:655:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [31:0]    watchdog;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:709:27]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire [7:0][2:0] _GEN_0 = '{3'h4, 3'h5, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};
    wire [7:0][2:0] _GEN_1 = '{3'h4, 3'h4, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};
    wire [5:0]      _is_aligned_mask_T = 6'h7 << io_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
    wire [2:0]      _GEN_2 = io_in_a_bits_address[2:0] & ~(_is_aligned_mask_T[2:0]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:16, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
    wire            mask_sub_sub_size = io_in_a_bits_size == 2'h2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
    wire            mask_sub_sub_0_1 = (&io_in_a_bits_size) | mask_sub_sub_size & ~(io_in_a_bits_address[2]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
    wire            mask_sub_sub_1_1 = (&io_in_a_bits_size) | mask_sub_sub_size & io_in_a_bits_address[2];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
    wire            mask_sub_size = io_in_a_bits_size == 2'h1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
    wire            mask_sub_0_2 = ~(io_in_a_bits_address[2]) & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_sub_0_1 = mask_sub_sub_0_1 | mask_sub_size & mask_sub_0_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_sub_1_2 = ~(io_in_a_bits_address[2]) & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_sub_1_1 = mask_sub_sub_0_1 | mask_sub_size & mask_sub_1_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_sub_2_2 = io_in_a_bits_address[2] & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
    wire            mask_sub_2_1 = mask_sub_sub_1_1 | mask_sub_size & mask_sub_2_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire            mask_sub_3_2 = io_in_a_bits_address[2] & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
    wire            mask_sub_3_1 = mask_sub_sub_1_1 | mask_sub_size & mask_sub_3_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
    wire [7:0]      mask = {mask_sub_3_1 | mask_sub_3_2 & io_in_a_bits_address[0], mask_sub_3_1 | mask_sub_3_2 & ~(io_in_a_bits_address[0]), mask_sub_2_1 | mask_sub_2_2 & io_in_a_bits_address[0], mask_sub_2_1 | mask_sub_2_2 & ~(io_in_a_bits_address[0]), mask_sub_1_1 | mask_sub_1_2 & io_in_a_bits_address[0], mask_sub_1_1 | mask_sub_1_2 & ~(io_in_a_bits_address[0]), mask_sub_0_1 | mask_sub_0_2 & io_in_a_bits_address[0], mask_sub_0_1 | mask_sub_0_2 & ~(io_in_a_bits_address[0])};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
    wire            _GEN_3 = io_in_a_valid & io_in_a_bits_opcode == 3'h6 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:{25,54}]
    wire            _GEN_4 = io_in_a_bits_source > 11'h40F;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20]
    wire            _GEN_5 = io_in_a_bits_size != 2'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
    wire            _GEN_6 = io_in_a_bits_param > 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire            _GEN_7 = io_in_a_bits_mask != 8'hFF;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:91:31]
    wire            _GEN_8 = io_in_a_valid & (&io_in_a_bits_opcode) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:{25,53}]
    wire            _GEN_9 = io_in_a_valid & io_in_a_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:{25,45}]
    wire            _GEN_10 = _GEN_9 & _GEN_4;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
    wire            _GEN_11 = io_in_a_bits_mask != mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
    wire            _GEN_12 = io_in_a_valid & io_in_a_bits_opcode == 3'h0 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:{25,53}]
    wire            _GEN_13 = io_in_a_valid & io_in_a_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:{25,56}]
    wire            _GEN_14 = io_in_a_valid & io_in_a_bits_opcode == 3'h2 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:{25,56}]
    wire            _GEN_15 = io_in_a_valid & io_in_a_bits_opcode == 3'h3 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:{25,53}]
    wire            _GEN_16 = io_in_a_valid & io_in_a_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:{25,46}]
    wire            _GEN_17 = io_in_a_valid & a_first_counter & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :392:19]
    wire            _GEN_18 = io_in_d_valid & d_first_counter & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :544:19]
    wire [4159:0]   _GEN_19 = {4147'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:637:44]
    wire [4159:0]   _a_opcode_lookup_T_1 = inflight_opcodes >> _GEN_19;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35, :637:44]
    wire            _GEN_20 = io_in_d_valid & ~d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:674:26]
    wire            same_cycle_resp = io_in_a_valid & ~a_first_counter_1 & io_in_a_bits_source == io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:651:26, :684:{88,113}]
    wire            _GEN_21 = _GEN_20 & same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :651:26, :674:26, :684:88, :687:30]
    wire            _GEN_22 = _GEN_20 & ~same_cycle_resp & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :651:26, :674:26, :684:88, :687:30]
    wire [1039:0]   _GEN_23 = inflight >> io_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27, :661:26]
    wire [1039:0]   _GEN_24 = inflight >> io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27, :685:25]
    wire [4159:0]   _a_size_lookup_T_1 = inflight_sizes >> _GEN_19;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33, :637:44, :641:40]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      if (_GEN_3) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & _GEN_5) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & _GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid grow param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, :91:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm from a client which does not support Probe (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & _GEN_5) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm smaller than a beat (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & _GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid grow param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & ~(|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, :102:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm requests NtoB (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :91:31, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_8 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Get type which master claims it can't emit (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & ~(io_in_a_bits_address[16])) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14, :45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Get type which slave claims it can't support (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & _GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, :113:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & _GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries PutPartial type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & (|(io_in_a_bits_mask & ~mask))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56, :130:{31,33,40}, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_14) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Arithmetic type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_14 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_14 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_14 & io_in_a_bits_param > 3'h4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:141:33, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_14 & _GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_15) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Logical type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_15 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_15 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_15 & io_in_a_bits_param[2]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:148:30, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_15 & _GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Hint type which is unexpected using diplomatic parameters (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & _GEN_4) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & (|_GEN_2)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint address not aligned to size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & (|(io_in_a_bits_param[2:1]))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:161:28, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint carries invalid opcode param (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & _GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint contains invalid mask (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_16 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint is corrupt (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (io_in_d_valid & ~reset & io_in_d_bits_source > 11'h40F) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel AccessAckData carries invalid source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_17 & io_in_a_bits_opcode != opcode) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :387:22, :392:19, :393:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel opcode changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & io_in_a_bits_param != param) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :388:22, :392:19, :394:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel param changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & io_in_a_bits_size != size) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :389:22, :392:19, :395:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & io_in_a_bits_source != source) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :390:22, :392:19, :396:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_17 & io_in_a_bits_address != address) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :391:22, :392:19, :397:32]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel address changed with multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_18 & io_in_d_bits_size != size_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :540:22, :544:19, :547:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel size changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_18 & io_in_d_bits_source != source_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :541:22, :544:19, :548:29]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel source changed within multibeat operation (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN & ~reset & _GEN_23[0]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :655:25, :661:26]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel re-used a source ID (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_20 & ~reset & ~(_GEN_24[0] | same_cycle_resp)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :651:26, :674:26, :684:88, :685:{25,49}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel acknowledged for nothing inflight (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_21 & ~(_GEN_1[io_in_a_bits_opcode] == 3'h1 | _GEN_0[io_in_a_bits_opcode] == 3'h1)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :687:30, :688:{38,77}, :689:39]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_21 & io_in_a_bits_size != io_in_d_bits_size) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :687:30, :690:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_22 & ~(_GEN_1[_a_opcode_lookup_T_1[3:1]] == 3'h1 | _GEN_0[_a_opcode_lookup_T_1[3:1]] == 3'h1)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :637:{44,152}, :687:30, :692:{38,72}, :693:38]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_22 & {2'h0, io_in_d_bits_size} != {1'h0, _a_size_lookup_T_1[3:1]}) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11, :641:{19,40,144}, :687:30, :694:36]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (_GEN_20 & ~a_first_counter_1 & io_in_a_valid & io_in_a_bits_source == io_in_d_bits_source & ~reset & ~(~io_in_d_ready | io_in_a_ready)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :52:11, :674:26, :697:{36,47,65,90}, :698:{15,32}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $error("Assertion failed: ready check\n    at Monitor.scala:52 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:52:11]
      end
      if (~reset & ~(inflight == 1040'h0 | _plusarg_reader_out == 32'h0 | watchdog < _plusarg_reader_out)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :614:27, :709:27, :712:{26,30,39,47,59}, generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: TileLink timeout expired (connected at generators/rocket-chip/src/main/scala/devices/tilelink/BootROM.scala:105:18)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [16398:0] _GEN_25 = {16386'h0, io_in_d_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76]
  wire [2047:0]  _d_clr_T = 2048'h1 << io_in_d_bits_source;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [2047:0]  _a_set_T = 2048'h1 << io_in_a_bits_source;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [16398:0] _d_opcodes_clr_T_5 = 16399'hF << _GEN_25;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76]
  wire [16386:0] _a_opcodes_set_T_1 = {16383'h0, _GEN ? {io_in_a_bits_opcode, 1'h1} : 4'h0} << {16374'h0, io_in_a_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:646:40, :655:{25,70}, :657:{28,61}, :659:54]
  wire [16398:0] _d_sizes_clr_T_5 = 16399'hF << _GEN_25;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:680:76, :681:74]
  wire [16385:0] _a_sizes_set_T_1 = {16383'h0, _GEN ? {io_in_a_bits_size, 1'h1} : 3'h0} << {16373'h0, io_in_a_bits_source, 2'h0};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:648:38, :655:{25,70}, :658:{28,59}, :659:54, :660:52]
  wire           d_first_done = io_in_d_ready & io_in_d_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire           _GEN_26 = d_first_done & ~d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:678:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      a_first_counter <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_first_counter <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      inflight <= 1040'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27]
      inflight_opcodes <= 4160'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35]
      inflight_sizes <= 4160'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33]
      a_first_counter_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_first_counter_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      watchdog <= 32'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:709:27]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      a_first_counter <= (~a_first_done | a_first_counter - 1'h1) & a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28, :235:17, :236:15, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      d_first_counter <= (~d_first_done | d_first_counter - 1'h1) & d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28, :235:17, :236:15, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      inflight <= (inflight | (_GEN ? _a_set_T[1039:0] : 1040'h0)) & ~(_GEN_26 ? _d_clr_T[1039:0] : 1040'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:614:27, :626:34, :655:{25,70}, :656:28, :664:34, :678:{25,89}, :679:21, :705:{27,36,38}, src/main/scala/chisel3/util/OneHot.scala:58:35]
      inflight_opcodes <= (inflight_opcodes | (_GEN ? _a_opcodes_set_T_1[4159:0] : 4160'h0)) & ~(_GEN_26 ? _d_opcodes_clr_T_5[4159:0] : 4160'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:616:35, :630:33, :655:{25,70}, :659:{28,54}, :668:33, :678:{25,89}, :680:{21,76}, :706:{43,60,62}]
      inflight_sizes <= (inflight_sizes | (_GEN ? _a_sizes_set_T_1[4159:0] : 4160'h0)) & ~(_GEN_26 ? _d_sizes_clr_T_5[4159:0] : 4160'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:618:33, :632:31, :655:{25,70}, :660:{28,52}, :670:31, :678:{25,89}, :681:{21,74}, :707:{39,54,56}]
      a_first_counter_1 <= (~a_first_done | a_first_counter_1 - 1'h1) & a_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28, :235:17, :236:15, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      d_first_counter_1 <= (~d_first_done | d_first_counter_1 - 1'h1) & d_first_counter_1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28, :235:17, :236:15, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      watchdog <= a_first_done | d_first_done ? 32'h0 : watchdog + 32'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:709:27, :714:{14,26}, :715:{25,43,54}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    if (a_first_done & ~a_first_counter) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:399:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      opcode <= io_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:387:22]
      param <= io_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:388:22]
      size <= io_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:389:22]
      source <= io_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:390:22]
      address <= io_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:391:22]
    end
    if (d_first_done & ~d_first_counter) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:552:18, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      size_1 <= io_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:540:22]
      source_1 <= io_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:541:22]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:295];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        for (logic [8:0] i = 9'h0; i < 9'h128; i += 9'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        end	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        a_first_counter = _RANDOM[9'h0][0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
        opcode = _RANDOM[9'h0][3:1];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :387:22]
        param = _RANDOM[9'h0][6:4];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :388:22]
        size = _RANDOM[9'h0][8:7];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :389:22]
        source = _RANDOM[9'h0][19:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :390:22]
        address = {_RANDOM[9'h0][31:20], _RANDOM[9'h1][4:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :391:22]
        d_first_counter = _RANDOM[9'h1][5];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :391:22]
        size_1 = _RANDOM[9'h1][12:11];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :391:22, :540:22]
        source_1 = _RANDOM[9'h1][23:13];	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :391:22, :541:22]
        inflight = {_RANDOM[9'h1][31:26], _RANDOM[9'h2], _RANDOM[9'h3], _RANDOM[9'h4], _RANDOM[9'h5], _RANDOM[9'h6], _RANDOM[9'h7], _RANDOM[9'h8], _RANDOM[9'h9], _RANDOM[9'hA], _RANDOM[9'hB], _RANDOM[9'hC], _RANDOM[9'hD], _RANDOM[9'hE], _RANDOM[9'hF], _RANDOM[9'h10], _RANDOM[9'h11], _RANDOM[9'h12], _RANDOM[9'h13], _RANDOM[9'h14], _RANDOM[9'h15], _RANDOM[9'h16], _RANDOM[9'h17], _RANDOM[9'h18], _RANDOM[9'h19], _RANDOM[9'h1A], _RANDOM[9'h1B], _RANDOM[9'h1C], _RANDOM[9'h1D], _RANDOM[9'h1E], _RANDOM[9'h1F], _RANDOM[9'h20], _RANDOM[9'h21], _RANDOM[9'h22][9:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :391:22, :614:27]
        inflight_opcodes =
          {_RANDOM[9'h22][31:10],
           _RANDOM[9'h23],
           _RANDOM[9'h24],
           _RANDOM[9'h25],
           _RANDOM[9'h26],
           _RANDOM[9'h27],
           _RANDOM[9'h28],
           _RANDOM[9'h29],
           _RANDOM[9'h2A],
           _RANDOM[9'h2B],
           _RANDOM[9'h2C],
           _RANDOM[9'h2D],
           _RANDOM[9'h2E],
           _RANDOM[9'h2F],
           _RANDOM[9'h30],
           _RANDOM[9'h31],
           _RANDOM[9'h32],
           _RANDOM[9'h33],
           _RANDOM[9'h34],
           _RANDOM[9'h35],
           _RANDOM[9'h36],
           _RANDOM[9'h37],
           _RANDOM[9'h38],
           _RANDOM[9'h39],
           _RANDOM[9'h3A],
           _RANDOM[9'h3B],
           _RANDOM[9'h3C],
           _RANDOM[9'h3D],
           _RANDOM[9'h3E],
           _RANDOM[9'h3F],
           _RANDOM[9'h40],
           _RANDOM[9'h41],
           _RANDOM[9'h42],
           _RANDOM[9'h43],
           _RANDOM[9'h44],
           _RANDOM[9'h45],
           _RANDOM[9'h46],
           _RANDOM[9'h47],
           _RANDOM[9'h48],
           _RANDOM[9'h49],
           _RANDOM[9'h4A],
           _RANDOM[9'h4B],
           _RANDOM[9'h4C],
           _RANDOM[9'h4D],
           _RANDOM[9'h4E],
           _RANDOM[9'h4F],
           _RANDOM[9'h50],
           _RANDOM[9'h51],
           _RANDOM[9'h52],
           _RANDOM[9'h53],
           _RANDOM[9'h54],
           _RANDOM[9'h55],
           _RANDOM[9'h56],
           _RANDOM[9'h57],
           _RANDOM[9'h58],
           _RANDOM[9'h59],
           _RANDOM[9'h5A],
           _RANDOM[9'h5B],
           _RANDOM[9'h5C],
           _RANDOM[9'h5D],
           _RANDOM[9'h5E],
           _RANDOM[9'h5F],
           _RANDOM[9'h60],
           _RANDOM[9'h61],
           _RANDOM[9'h62],
           _RANDOM[9'h63],
           _RANDOM[9'h64],
           _RANDOM[9'h65],
           _RANDOM[9'h66],
           _RANDOM[9'h67],
           _RANDOM[9'h68],
           _RANDOM[9'h69],
           _RANDOM[9'h6A],
           _RANDOM[9'h6B],
           _RANDOM[9'h6C],
           _RANDOM[9'h6D],
           _RANDOM[9'h6E],
           _RANDOM[9'h6F],
           _RANDOM[9'h70],
           _RANDOM[9'h71],
           _RANDOM[9'h72],
           _RANDOM[9'h73],
           _RANDOM[9'h74],
           _RANDOM[9'h75],
           _RANDOM[9'h76],
           _RANDOM[9'h77],
           _RANDOM[9'h78],
           _RANDOM[9'h79],
           _RANDOM[9'h7A],
           _RANDOM[9'h7B],
           _RANDOM[9'h7C],
           _RANDOM[9'h7D],
           _RANDOM[9'h7E],
           _RANDOM[9'h7F],
           _RANDOM[9'h80],
           _RANDOM[9'h81],
           _RANDOM[9'h82],
           _RANDOM[9'h83],
           _RANDOM[9'h84],
           _RANDOM[9'h85],
           _RANDOM[9'h86],
           _RANDOM[9'h87],
           _RANDOM[9'h88],
           _RANDOM[9'h89],
           _RANDOM[9'h8A],
           _RANDOM[9'h8B],
           _RANDOM[9'h8C],
           _RANDOM[9'h8D],
           _RANDOM[9'h8E],
           _RANDOM[9'h8F],
           _RANDOM[9'h90],
           _RANDOM[9'h91],
           _RANDOM[9'h92],
           _RANDOM[9'h93],
           _RANDOM[9'h94],
           _RANDOM[9'h95],
           _RANDOM[9'h96],
           _RANDOM[9'h97],
           _RANDOM[9'h98],
           _RANDOM[9'h99],
           _RANDOM[9'h9A],
           _RANDOM[9'h9B],
           _RANDOM[9'h9C],
           _RANDOM[9'h9D],
           _RANDOM[9'h9E],
           _RANDOM[9'h9F],
           _RANDOM[9'hA0],
           _RANDOM[9'hA1],
           _RANDOM[9'hA2],
           _RANDOM[9'hA3],
           _RANDOM[9'hA4][9:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :614:27, :616:35]
        inflight_sizes =
          {_RANDOM[9'hA4][31:10],
           _RANDOM[9'hA5],
           _RANDOM[9'hA6],
           _RANDOM[9'hA7],
           _RANDOM[9'hA8],
           _RANDOM[9'hA9],
           _RANDOM[9'hAA],
           _RANDOM[9'hAB],
           _RANDOM[9'hAC],
           _RANDOM[9'hAD],
           _RANDOM[9'hAE],
           _RANDOM[9'hAF],
           _RANDOM[9'hB0],
           _RANDOM[9'hB1],
           _RANDOM[9'hB2],
           _RANDOM[9'hB3],
           _RANDOM[9'hB4],
           _RANDOM[9'hB5],
           _RANDOM[9'hB6],
           _RANDOM[9'hB7],
           _RANDOM[9'hB8],
           _RANDOM[9'hB9],
           _RANDOM[9'hBA],
           _RANDOM[9'hBB],
           _RANDOM[9'hBC],
           _RANDOM[9'hBD],
           _RANDOM[9'hBE],
           _RANDOM[9'hBF],
           _RANDOM[9'hC0],
           _RANDOM[9'hC1],
           _RANDOM[9'hC2],
           _RANDOM[9'hC3],
           _RANDOM[9'hC4],
           _RANDOM[9'hC5],
           _RANDOM[9'hC6],
           _RANDOM[9'hC7],
           _RANDOM[9'hC8],
           _RANDOM[9'hC9],
           _RANDOM[9'hCA],
           _RANDOM[9'hCB],
           _RANDOM[9'hCC],
           _RANDOM[9'hCD],
           _RANDOM[9'hCE],
           _RANDOM[9'hCF],
           _RANDOM[9'hD0],
           _RANDOM[9'hD1],
           _RANDOM[9'hD2],
           _RANDOM[9'hD3],
           _RANDOM[9'hD4],
           _RANDOM[9'hD5],
           _RANDOM[9'hD6],
           _RANDOM[9'hD7],
           _RANDOM[9'hD8],
           _RANDOM[9'hD9],
           _RANDOM[9'hDA],
           _RANDOM[9'hDB],
           _RANDOM[9'hDC],
           _RANDOM[9'hDD],
           _RANDOM[9'hDE],
           _RANDOM[9'hDF],
           _RANDOM[9'hE0],
           _RANDOM[9'hE1],
           _RANDOM[9'hE2],
           _RANDOM[9'hE3],
           _RANDOM[9'hE4],
           _RANDOM[9'hE5],
           _RANDOM[9'hE6],
           _RANDOM[9'hE7],
           _RANDOM[9'hE8],
           _RANDOM[9'hE9],
           _RANDOM[9'hEA],
           _RANDOM[9'hEB],
           _RANDOM[9'hEC],
           _RANDOM[9'hED],
           _RANDOM[9'hEE],
           _RANDOM[9'hEF],
           _RANDOM[9'hF0],
           _RANDOM[9'hF1],
           _RANDOM[9'hF2],
           _RANDOM[9'hF3],
           _RANDOM[9'hF4],
           _RANDOM[9'hF5],
           _RANDOM[9'hF6],
           _RANDOM[9'hF7],
           _RANDOM[9'hF8],
           _RANDOM[9'hF9],
           _RANDOM[9'hFA],
           _RANDOM[9'hFB],
           _RANDOM[9'hFC],
           _RANDOM[9'hFD],
           _RANDOM[9'hFE],
           _RANDOM[9'hFF],
           _RANDOM[9'h100],
           _RANDOM[9'h101],
           _RANDOM[9'h102],
           _RANDOM[9'h103],
           _RANDOM[9'h104],
           _RANDOM[9'h105],
           _RANDOM[9'h106],
           _RANDOM[9'h107],
           _RANDOM[9'h108],
           _RANDOM[9'h109],
           _RANDOM[9'h10A],
           _RANDOM[9'h10B],
           _RANDOM[9'h10C],
           _RANDOM[9'h10D],
           _RANDOM[9'h10E],
           _RANDOM[9'h10F],
           _RANDOM[9'h110],
           _RANDOM[9'h111],
           _RANDOM[9'h112],
           _RANDOM[9'h113],
           _RANDOM[9'h114],
           _RANDOM[9'h115],
           _RANDOM[9'h116],
           _RANDOM[9'h117],
           _RANDOM[9'h118],
           _RANDOM[9'h119],
           _RANDOM[9'h11A],
           _RANDOM[9'h11B],
           _RANDOM[9'h11C],
           _RANDOM[9'h11D],
           _RANDOM[9'h11E],
           _RANDOM[9'h11F],
           _RANDOM[9'h120],
           _RANDOM[9'h121],
           _RANDOM[9'h122],
           _RANDOM[9'h123],
           _RANDOM[9'h124],
           _RANDOM[9'h125],
           _RANDOM[9'h126][9:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :616:35, :618:33]
        a_first_counter_1 = _RANDOM[9'h126][10];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :618:33]
        d_first_counter_1 = _RANDOM[9'h126][11];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :618:33]
        watchdog = {_RANDOM[9'h126][31:12], _RANDOM[9'h127][11:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7, :618:33, :709:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
endmodule

